//! Cross-platform validated working-directory capability for launching child
//! processes (git subcommands, the agent) *through a pinned directory handle*
//! rather than by re-resolving a cwd *path* at spawn time.
//!
//! # Why
//!
//! #25 hardened the run-dir *creation* path: on Linux the runs root is pinned
//! with `openat2(RESOLVE_NO_SYMLINKS)` and the per-job dir is created relative
//! to that handle. But the follow-on **launches** — `git clone`/`fetch`/
//! `checkout` and the agent itself — still took the run dir as a `current_dir`
//! *path*, so the kernel re-resolved that path in the forked child right before
//! `exec`. On a shared host where the runs root can sit under a world-writable
//! ancestor, a same-UID actor can swap an ancestor component for a symlink in
//! the window between the provisioning check and the launch, redirecting the
//! child's cwd (and therefore its clone target / working tree) outside the
//! validated tree. No amount of *re-checking the path* closes that window —
//! each check is a fresh, non-atomic resolution (#35).
//!
//! # How
//!
//! Resolve the directory **once**, no-follow, into a pinned fd, then `fchdir`
//! to that fd in the child's `pre_exec` hook. The child's cwd becomes the
//! validated inode, immune to any later component swap: a rename of an
//! already-opened component cannot move the pinned inode, and a component
//! swapped to a symlink *before* it is opened is refused by the no-follow open
//! (the launch fails rather than escaping).
//!
//! Resolution is no-symlink on every supported host:
//! - **Linux ≥5.6**: `openat2(RESOLVE_NO_SYMLINKS)` refuses the whole path if
//!   any component is a symlink, in one atomic kernel resolution.
//! - **macOS / older Linux**: an `O_NOFOLLOW` `openat` chain walked component by
//!   component (the cap-std style). `O_NOFOLLOW` refuses a symlink at each
//!   `openat`'s own final component, so chaining the opens covers the whole
//!   path — and each descent is pinned by the fd we already hold, so a rename of
//!   a component we have passed cannot redirect the remainder.
//!
//! On a non-Unix host (no `fchdir`/`pre_exec`) this degrades to the prior
//! `current_dir(path)` behaviour; those targets are not supported daemon hosts.

use std::io;
use std::path::{Path, PathBuf};

/// Lexically resolve a run-directory path to an absolute path, **without
/// touching the filesystem** (no symlink is ever followed), resolving only
/// *leading* `..` against the trusted anchor and **refusing any interior `..`**.
///
/// This runs at the run-path *input boundary* (the slot resolving
/// `<runs_dir>/<key>`). A *leading* `..` (operator shorthand such as
/// `--runs-dir ../runs`) is resolved against the trusted current directory
/// lexically — a parent component traverses the *directory entry*, never a
/// symlink, and the anchor is the process cwd — so a parent-relative
/// `--runs-dir` keeps working on every backend. But an **interior** `..` (one
/// that follows a normal component) is REFUSED, never collapsed: run paths are
/// generated by us and never legitimately contain `..`, and a lexical collapse
/// is unsafe across a symlinked component. Collapsing `/shared/link/../runs`
/// to `/shared/runs` when `link` is a symlink would rewrite the path *before*
/// the no-follow chain can inspect `link`, so the sweep would land outside the
/// symlinked input instead of refusing it. Failing closed keeps the lexical
/// result and the no-follow backends enforcing one consistent policy.
///
/// A relative input is anchored at the current directory first (the same
/// anchor the launch backends resolve a relative path against). Like the
/// kernel, a leading `..` at the filesystem root is a no-op (clamps at `/`).
pub(crate) fn normalize_run_path(path: &Path) -> io::Result<PathBuf> {
    use std::path::Component;
    // Anchor: an absolute input anchors at its own root; a relative input
    // anchors at the trusted process cwd. Leading `..` climbs this anchor
    // lexically; an interior `..` (after a normal component) is refused.
    let mut out: PathBuf = if path.is_absolute() {
        let mut root = PathBuf::new();
        for comp in path.components() {
            match comp {
                Component::Prefix(p) => root.push(p.as_os_str()),
                Component::RootDir => {
                    root.push(comp.as_os_str());
                    break;
                }
                _ => break,
            }
        }
        root
    } else {
        std::env::current_dir()?
    };
    let mut seen_normal = false;
    for comp in path.components() {
        match comp {
            // The root/prefix is already captured in `out`.
            Component::Prefix(_) | Component::RootDir => {}
            Component::CurDir => {}
            Component::Normal(name) => {
                seen_normal = true;
                out.push(name);
            }
            Component::ParentDir => {
                if seen_normal {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        "run path must not contain an interior `..` component",
                    ));
                }
                // Leading `..`: climb the trusted anchor lexically (a parent
                // entry is never a symlink), clamping at the root like the
                // kernel rather than escaping above it.
                let _ = out.pop();
                if out.as_os_str().is_empty() {
                    out.push(Component::RootDir.as_os_str());
                }
            }
        }
    }
    Ok(out)
}

/// Lexically resolve a run path to the SAME absolute, `.`-/`..`-collapsed form
/// [`normalize_run_path`] produces for a valid run path — but NEVER refuse:
/// where `normalize_run_path` rejects an interior `..` (fail-closed for
/// VALIDATING operator/run input at the trust boundary), this resolver
/// collapses it lexically instead. Use it only to derive a COMPARISON key that
/// must match a path `normalize_run_path` already registered (e.g. the
/// retention sweep's `active_runs` lookups), never to validate a path before
/// trusting it: a lexical `name/..` collapse is unsafe across a symlinked
/// component, which is exactly why validation refuses it. Purely lexical —
/// touches no filesystem, follows no symlink.
pub(crate) fn resolve_run_path(path: &Path) -> io::Result<PathBuf> {
    use std::path::Component;
    let mut out: PathBuf = if path.is_absolute() {
        let mut root = PathBuf::new();
        for comp in path.components() {
            match comp {
                Component::Prefix(p) => root.push(p.as_os_str()),
                Component::RootDir => {
                    root.push(comp.as_os_str());
                    break;
                }
                _ => break,
            }
        }
        root
    } else {
        std::env::current_dir()?
    };
    for comp in path.components() {
        match comp {
            Component::Prefix(_) | Component::RootDir | Component::CurDir => {}
            Component::Normal(name) => out.push(name),
            // Collapse `..` lexically wherever it appears, clamping at the
            // root like the kernel rather than escaping above it.
            Component::ParentDir => {
                let _ = out.pop();
                if out.as_os_str().is_empty() {
                    out.push(Component::RootDir.as_os_str());
                }
            }
        }
    }
    Ok(out)
}

/// A directory resolved no-follow and pinned by its fd, used to launch a child
/// with its cwd set to the validated inode (via `fchdir` in `pre_exec`) rather
/// than by re-resolving a path at spawn time.
//
// `Debug` is derived so callers can `unwrap_err()` a `Result<CwdHandle, _>`
// (e.g. the pinned-open refusal tests in `slot.rs`): `unwrap_err` requires the
// success type to be `Debug`. Both fields are `Debug` on every platform.
#[derive(Debug)]
pub(crate) struct CwdHandle {
    /// The path the handle was resolved from — the non-Unix `current_dir`
    /// fallback target (on Unix the launch binds the pinned fd, not a path).
    #[cfg(not(unix))]
    path: std::path::PathBuf,
    #[cfg(unix)]
    fd: std::os::unix::io::OwnedFd,
}

#[cfg(unix)]
impl Clone for CwdHandle {
    /// A second handle to the SAME pinned inode (a close-on-exec dup of the
    /// fd), so the capability can be carried by several consumers (the agent
    /// launch, the HEAD probes) without re-resolving the path.
    ///
    /// `Clone` cannot fail, so a dup failure (e.g. descriptor exhaustion,
    /// `EMFILE`) is panicked on here — prefer [`CwdHandle::try_clone`] at
    /// callers that can propagate, so an exhausted fd table surfaces as a
    /// normal job error rather than a worker-crashing panic.
    fn clone(&self) -> Self {
        self.try_clone().expect("dup the pinned directory fd")
    }
}

#[cfg(not(unix))]
impl Clone for CwdHandle {
    fn clone(&self) -> Self {
        CwdHandle {
            path: self.path.clone(),
        }
    }
}

impl CwdHandle {
    /// Fallible [`Clone`]: a second handle to the SAME pinned inode (a
    /// close-on-exec dup of the fd), propagating a dup failure (e.g.
    /// descriptor exhaustion, `EMFILE`) instead of panicking. Prefer this at
    /// callers that can return an error, so an exhausted fd table becomes a
    /// normal job error rather than a worker crash.
    #[cfg(unix)]
    pub(crate) fn try_clone(&self) -> io::Result<CwdHandle> {
        Ok(CwdHandle { fd: self.dup_fd()? })
    }

    /// Non-Unix `try_clone`: there is no fd to dup, so cloning the retained
    /// path cannot fail — mirror the non-Unix [`Clone`] and return `Ok`. This
    /// keeps `slot::execute`'s unconditional `try_clone()` calls (the agent
    /// directory and both HEAD probes) compiling on non-Unix hosts, where the
    /// launch falls back to the validated path.
    #[cfg(not(unix))]
    pub(crate) fn try_clone(&self) -> io::Result<CwdHandle> {
        Ok(CwdHandle {
            path: self.path.clone(),
        })
    }

    /// Wrap an already-pinned, no-follow directory fd — e.g. the child handle a
    /// run-dir preparation pinned — as a `CwdHandle`, without re-resolving any
    /// path. Lets preparation hand its exact validated inode straight to the
    /// launch rather than reopening the run dir by name, which a same-UID actor
    /// could have swapped for an ordinary tree in between (#35).
    #[cfg(unix)]
    pub(crate) fn from_fd(fd: std::os::unix::io::OwnedFd) -> CwdHandle {
        CwdHandle { fd }
    }

    /// Resolve `path` as a directory without following a symlink at any
    /// component and pin the result. A symlinked component anywhere in `path`
    /// is refused (so the caller's launch fails closed instead of escaping the
    /// validated tree); a missing directory or a non-directory target is an
    /// error.
    ///
    /// On Unix, production preparation carries the pinned fd it created
    /// (`from_fd`) rather than reopening by path, so this path-resolution open
    /// is reached only by the tests (and the non-Unix fallback below).
    #[cfg(unix)]
    #[cfg_attr(not(test), allow(dead_code))]
    pub(crate) fn open(path: &Path) -> io::Result<CwdHandle> {
        let fd = open_nofollow(path)?;
        Ok(CwdHandle { fd })
    }

    /// Non-Unix `open`: no `fchdir`/`pre_exec`, so fall back to validating the
    /// leaf is not a symlink and then using the path. Best-effort — these are
    /// not supported daemon hosts.
    #[cfg(not(unix))]
    pub(crate) fn open(path: &Path) -> io::Result<CwdHandle> {
        let meta = std::fs::symlink_metadata(path)?;
        if meta.file_type().is_symlink() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "refusing symlinked working directory",
            ));
        }
        Ok(CwdHandle {
            path: path.to_path_buf(),
        })
    }

    /// Arm `cmd` to enter this pinned directory in the forked child before
    /// `exec`. On Unix this installs a `pre_exec` `fchdir` on a close-on-exec
    /// dup of the pinned fd, so the child's cwd is the validated inode and no
    /// path is re-resolved; on other hosts it sets `current_dir` to the
    /// (leaf-validated) path.
    #[cfg(unix)]
    pub(crate) fn apply(&self, cmd: &mut tokio::process::Command) -> io::Result<()> {
        // SAFETY: `pre_exec` runs in the forked child before `exec`; we only
        // call the async-signal-safe `fchdir` and touch no Rust allocator state.
        unsafe {
            arm_fchdir(cmd.as_std_mut(), self.dup_fd()?);
        }
        Ok(())
    }

    #[cfg(not(unix))]
    pub(crate) fn apply(&self, cmd: &mut tokio::process::Command) -> io::Result<()> {
        cmd.current_dir(&self.path);
        Ok(())
    }

    /// `apply`, for a synchronous [`std::process::Command`]. The bounded
    /// `git rev-parse HEAD` probe (`slot::git_head_timeout`) drives its child
    /// synchronously, and the tests drive one too; both bind the pinned fd the
    /// same way the async [`apply`](Self::apply) does.
    #[cfg(unix)]
    pub(crate) fn apply_std(&self, cmd: &mut std::process::Command) -> io::Result<()> {
        // SAFETY: as `apply` — async-signal-safe `fchdir` in the pre-exec child.
        unsafe {
            arm_fchdir(cmd, self.dup_fd()?);
        }
        Ok(())
    }

    #[cfg(not(unix))]
    pub(crate) fn apply_std(&self, cmd: &mut std::process::Command) -> io::Result<()> {
        cmd.current_dir(&self.path);
        Ok(())
    }

    /// Pin a direct child directory of this handle, never following a symlink
    /// at the child and never leaving this directory. Because the open is
    /// anchored on the pinned fd, a rename or symlink swap of any *ancestor*
    /// cannot redirect it, and a same-UID actor replacing the child itself
    /// between provisioning and this open is bound to whatever the name
    /// resolves to *now* — so the launch that then binds the returned handle
    /// can never land in a tree swapped in afterwards. `name` must be a single
    /// path component.
    #[cfg(unix)]
    pub(crate) fn open_child(&self, name: &std::ffi::OsStr) -> io::Result<CwdHandle> {
        use std::ffi::CString;
        use std::os::unix::ffi::OsStrExt;
        use std::os::unix::io::{AsRawFd, FromRawFd, OwnedFd};
        let name_bytes = name.as_bytes();
        if name_bytes.is_empty()
            || name_bytes.contains(&b'/')
            || name_bytes == b"."
            || name_bytes == b".."
        {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "open_child expects a single path component",
            ));
        }
        let c = CString::new(name_bytes)
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "path component has NUL"))?;
        let fd = unsafe {
            libc::openat(
                self.fd.as_raw_fd(),
                c.as_ptr(),
                libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
            )
        };
        if fd < 0 {
            return Err(io::Error::last_os_error());
        }
        // SAFETY: `fd` is a fresh, owned descriptor just returned by `openat`.
        Ok(CwdHandle {
            fd: unsafe { OwnedFd::from_raw_fd(fd) },
        })
    }

    #[cfg(not(unix))]
    pub(crate) fn open_child(&self, name: &std::ffi::OsStr) -> io::Result<CwdHandle> {
        let path = self.path.join(name);
        let meta = std::fs::symlink_metadata(&path)?;
        if meta.file_type().is_symlink() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "refusing symlinked working directory",
            ));
        }
        Ok(CwdHandle { path })
    }

    /// The absolute path of the pinned directory *right now*, recovered through
    /// the fd rather than remembered from resolution time, so it still names
    /// the pinned inode after an ancestor rename. Used where a path string is
    /// genuinely required — the ACP `session/new` `cwd` — so the value sent to
    /// the agent is the same directory the launch bound, never a pre-swap
    /// pathname. On non-Unix hosts this is the (leaf-validated) path the handle
    /// was opened from.
    ///
    /// Recovery MUST NOT mutate the process-global cwd: the supervisor runs a
    /// multi-threaded Tokio runtime (`main`), so a transient `fchdir` into the
    /// pinned dir would make any *other* thread's concurrent relative-path
    /// operation resolve against the pinned run dir instead of the real cwd.
    /// Linux reads the fd's current name straight from `/proc/self/fd/<fd>` and
    /// macOS via `fcntl(F_GETPATH)` — neither touches the cwd. When neither
    /// non-mutating recovery is available (a Unix host without procfs or
    /// `F_GETPATH`, or a Linux pinned directory that has since been deleted),
    /// this **fails closed** with an error rather than falling back to an
    /// `fchdir` that would mutate the supervisor's process-global cwd: the
    /// caller surfaces the error (the launch / ACP handoff fails) instead of
    /// racing unrelated threads' path resolution.
    #[cfg(unix)]
    pub(crate) fn path(&self) -> io::Result<PathBuf> {
        #[cfg(target_os = "linux")]
        {
            if let Some(p) = self.path_via_proc() {
                return Ok(p);
            }
        }
        #[cfg(target_os = "macos")]
        {
            if let Some(p) = self.path_via_fgetpath() {
                return Ok(p);
            }
        }
        Err(io::Error::other(
            "cannot recover the pinned directory path without mutating the \
             process-global cwd (procfs/F_GETPATH unavailable, or the directory \
             was deleted)",
        ))
    }

    /// Linux: recover the pinned fd's current name from procfs — no cwd change.
    /// Returns `None` (so the caller fails closed) if procfs is unavailable or
    /// the link is not a plain absolute path, e.g. a deleted directory whose
    /// link carries a trailing `" (deleted)"`.
    #[cfg(all(unix, target_os = "linux"))]
    fn path_via_proc(&self) -> Option<PathBuf> {
        use std::os::unix::ffi::OsStrExt;
        use std::os::unix::io::AsRawFd;
        let link = format!("/proc/self/fd/{}", self.fd.as_raw_fd());
        let target = std::fs::read_link(link).ok()?;
        let bytes = target.as_os_str().as_bytes();
        if !target.is_absolute() || bytes.ends_with(b" (deleted)") {
            return None;
        }
        Some(target)
    }

    /// macOS: recover the pinned fd's current name via `fcntl(F_GETPATH)` — no
    /// cwd change. Returns `None` on failure so the caller falls back.
    #[cfg(all(unix, target_os = "macos"))]
    fn path_via_fgetpath(&self) -> Option<PathBuf> {
        use std::os::unix::ffi::OsStrExt;
        use std::os::unix::io::AsRawFd;
        let mut buf = vec![0u8; libc::PATH_MAX as usize];
        // SAFETY: `buf` is writable for its (PATH_MAX) length; `F_GETPATH`
        // writes a NUL-terminated absolute path into it and changes no cwd.
        let rc = unsafe {
            libc::fcntl(
                self.fd.as_raw_fd(),
                libc::F_GETPATH,
                buf.as_mut_ptr().cast::<libc::c_char>(),
            )
        };
        if rc != 0 {
            return None;
        }
        let len = buf.iter().position(|&b| b == 0)?;
        Some(PathBuf::from(
            std::ffi::OsStr::from_bytes(&buf[..len]).to_os_string(),
        ))
    }

    #[cfg(not(unix))]
    pub(crate) fn path(&self) -> io::Result<PathBuf> {
        Ok(self.path.clone())
    }

    /// A close-on-exec dup of the pinned fd, moved into each `pre_exec` closure
    /// so the child-side `fchdir` target is owned by the `Command` itself and
    /// stays valid through the fork regardless of when this handle is dropped.
    ///
    /// The dup is allocated at descriptor **3 or above**: with a minimum of 0 a
    /// closed standard descriptor would let the dup occupy stdin/stdout/stderr,
    /// and the child's stdio setup can then replace that descriptor before
    /// `pre_exec` runs — leaving `fchdir` aimed at a pipe or `/dev/null`
    /// instead of the pinned directory (the launch fails with `ENOTDIR`).
    #[cfg(unix)]
    fn dup_fd(&self) -> io::Result<std::os::unix::io::OwnedFd> {
        use std::os::unix::io::{AsRawFd, FromRawFd, OwnedFd};
        let new = unsafe { libc::fcntl(self.fd.as_raw_fd(), libc::F_DUPFD_CLOEXEC, 3) };
        if new < 0 {
            return Err(io::Error::last_os_error());
        }
        // SAFETY: `new` is a fresh, owned fd just returned by `fcntl`.
        Ok(unsafe { OwnedFd::from_raw_fd(new) })
    }

    /// A close-on-exec dup of the pinned directory fd, for a consumer that
    /// needs to operate *relative to this exact validated inode* through a
    /// different fd-relative API (e.g. wrapping it in a
    /// [`crate::saferoot::DirHandle`] via `DirHandle::from_fd` to seed children
    /// without reopening the run dir by path (#35/#46)). `F_DUPFD_CLOEXEC`
    /// behaves like `dup`: the new fd shares the same open file description —
    /// and thus the directory offset/file position — with `self.fd`, exactly as
    /// documented for `dup` in `saferoot`'s directory enumeration. That
    /// shared offset is harmless here because the dup is only ever used for
    /// fd-relative operations (`openat*`), which ignore the file position; the
    /// returned fd is owned by the caller.
    #[cfg(target_os = "linux")]
    pub(crate) fn try_clone_fd(&self) -> io::Result<std::os::unix::io::OwnedFd> {
        self.dup_fd()
    }
}

/// Install a `pre_exec` hook that `fchdir`s into `fd` (consumed by the closure,
/// so it survives the fork and is closed with the `Command`). The fd is
/// close-on-exec, so it never leaks into the exec'd child — `fchdir` runs
/// *before* `exec` while the fd is still open.
#[cfg(unix)]
unsafe fn arm_fchdir<C: UnixCommandExt>(cmd: &mut C, fd: std::os::unix::io::OwnedFd) {
    use std::os::unix::io::AsRawFd;
    cmd.pre_exec_hook(move || {
        if libc::fchdir(fd.as_raw_fd()) != 0 {
            return Err(io::Error::last_os_error());
        }
        Ok(())
    });
}

/// Abstracts `std::os::unix::process::CommandExt::pre_exec` across the sync
/// `std::process::Command` and tokio's `&mut std::process::Command` view so the
/// `fchdir` hook is installed the same way for both.
#[cfg(unix)]
trait UnixCommandExt {
    unsafe fn pre_exec_hook<F>(&mut self, f: F)
    where
        F: FnMut() -> io::Result<()> + Send + Sync + 'static;
}

#[cfg(unix)]
impl UnixCommandExt for std::process::Command {
    unsafe fn pre_exec_hook<F>(&mut self, f: F)
    where
        F: FnMut() -> io::Result<()> + Send + Sync + 'static,
    {
        use std::os::unix::process::CommandExt;
        self.pre_exec(f);
    }
}

/// Resolve `path` to a pinned directory fd without following any symlink.
#[cfg(unix)]
fn open_nofollow(path: &Path) -> io::Result<std::os::unix::io::OwnedFd> {
    #[cfg(target_os = "linux")]
    {
        match open_nofollow_openat2(path) {
            Ok(fd) => return Ok(fd),
            // Pre-5.6 kernel without `openat2`: fall back to the portable
            // `O_NOFOLLOW` `openat` chain, which gives the same no-symlink
            // guarantee component by component.
            Err(e) if e.raw_os_error() == Some(libc::ENOSYS) => {}
            Err(e) => return Err(e),
        }
    }
    open_nofollow_chain(path)
}

/// `openat2(RESOLVE_NO_SYMLINKS)` — one atomic resolution that refuses the whole
/// path if any component is a symlink. `RESOLVE_BENEATH` is intentionally not
/// set: `path` is absolute, so the resolution must be allowed to start from
/// `/` (mirroring `saferoot::DirHandle::open_root_nofollow`).
#[cfg(target_os = "linux")]
fn open_nofollow_openat2(path: &Path) -> io::Result<std::os::unix::io::OwnedFd> {
    use std::ffi::CString;
    use std::os::unix::ffi::OsStrExt;
    use std::os::unix::io::{FromRawFd, OwnedFd};

    // `struct open_how` (linux/openat2.h). `libc::open_how` is `#[non_exhaustive]`
    // and cannot be built with a struct literal, so this is a byte-compatible
    // local mirror passed to the raw syscall.
    #[repr(C)]
    struct OpenHow {
        flags: u64,
        mode: u64,
        resolve: u64,
    }
    const RESOLVE_NO_SYMLINKS: u64 = 0x04;

    let c = CString::new(path.as_os_str().as_bytes())
        .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "path has NUL"))?;
    let how = OpenHow {
        flags: (libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC) as u64,
        mode: 0,
        resolve: RESOLVE_NO_SYMLINKS,
    };
    // SAFETY: `how` outlives the call and its size is passed explicitly; a
    // non-negative return is a fresh, owned fd.
    let ret = unsafe {
        libc::syscall(
            libc::SYS_openat2,
            libc::AT_FDCWD,
            c.as_ptr(),
            &how as *const OpenHow,
            std::mem::size_of::<OpenHow>(),
        )
    };
    if ret < 0 {
        return Err(io::Error::last_os_error());
    }
    // SAFETY: `ret` is a valid, freshly opened fd we now own.
    Ok(unsafe { OwnedFd::from_raw_fd(ret as i32) })
}

/// Portable no-symlink resolution: open each path component with `O_NOFOLLOW`
/// relative to the handle for the component before it. `O_NOFOLLOW` fails the
/// `openat` when that component is a symlink, so walking the whole path refuses
/// a symlink anywhere in it — and because each descent is anchored on the fd we
/// already hold, a rename of a component we have passed cannot redirect the
/// remainder.
#[cfg(unix)]
fn open_nofollow_chain(path: &Path) -> io::Result<std::os::unix::io::OwnedFd> {
    use std::ffi::CString;
    use std::os::unix::ffi::OsStrExt;
    use std::os::unix::io::{AsRawFd, FromRawFd, OwnedFd};
    use std::path::Component;

    fn open_dir(name: &std::ffi::CStr, flags: i32) -> io::Result<OwnedFd> {
        let fd = unsafe { libc::open(name.as_ptr(), flags) };
        if fd < 0 {
            return Err(io::Error::last_os_error());
        }
        Ok(unsafe { OwnedFd::from_raw_fd(fd) })
    }
    fn openat_dir(dirfd: i32, name: &std::ffi::CStr, flags: i32) -> io::Result<OwnedFd> {
        let fd = unsafe { libc::openat(dirfd, name.as_ptr(), flags) };
        if fd < 0 {
            return Err(io::Error::last_os_error());
        }
        Ok(unsafe { OwnedFd::from_raw_fd(fd) })
    }

    /// Is this fd a symlink? Used on Linux to catch a symlinked intermediate:
    /// the traversal-only `O_PATH` open does not fail on a symlink (it opens
    /// the link itself), so the no-follow guarantee must be enforced with an
    /// `fstat` after the open. Only the intermediate `O_PATH` fds are checked;
    /// the leaf and the non-Linux backends refuse a symlink at the `openat`.
    #[cfg(target_os = "linux")]
    fn fd_is_symlink(fd: &OwnedFd) -> io::Result<bool> {
        let mut st: libc::stat = unsafe { std::mem::zeroed() };
        // SAFETY: `st` is a valid, writable `stat`; `fd` is a live descriptor.
        if unsafe { libc::fstat(fd.as_raw_fd(), &mut st) } < 0 {
            return Err(io::Error::last_os_error());
        }
        Ok(st.st_mode & libc::S_IFMT == libc::S_IFLNK)
    }

    // Flags for the FINAL component (the directory we pin and hand back). The
    // leaf is opened `O_RDONLY` because the returned fd is used for more than
    // traversal: `fchdir` into it at launch, `/proc/self/fd` / `F_GETPATH`
    // path recovery, and `open_child` re-anchoring all want a real readable
    // directory handle. `O_NOFOLLOW` refuses a symlinked leaf.
    let base_flags = libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC;
    let step_flags = base_flags | libc::O_NOFOLLOW;

    // Flags for INTERMEDIATE components, which we only ever traverse *through*
    // to reach the next component — never read, never `fchdir`, never hand
    // back. Opening those `O_RDONLY` would require **read** permission on every
    // ancestor, where ordinary path traversal needs only **search** (execute)
    // permission: a run directory beneath a search-only ancestor (mode `0111`,
    // no read bit) would then fail the walk with `EACCES` even though the leaf
    // itself is reachable. The Linux `openat2` backend imposes no such extra
    // ancestor-read requirement, so this chain must not either. Use a
    // traversal-only open for the intermediates and reserve `O_RDONLY` for the
    // leaf.
    //
    // The traversal-only open is platform-specific, and on Linux it changes how
    // a symlinked intermediate is caught:
    // - Linux: `O_PATH` obtains a handle referencing the location without
    //   needing read *or* search permission on the component, and it can serve
    //   as the `dirfd` for the next `openat`. But `O_PATH` changes `O_NOFOLLOW`
    //   semantics: instead of *failing* on a symlink it opens the symlink
    //   itself, so the walk must detect that with an `fstat` `S_ISLNK` check
    //   (below) and refuse — otherwise the no-follow guarantee would be lost.
    //   (`O_PATH` fds reject `fchdir`/`read`, which is exactly why they are
    //   used only for intermediates, never the leaf.)
    // - macOS (no `O_PATH`): `O_SEARCH` opens the directory with search-only
    //   access — enough to use as the next `openat`'s `dirfd` — without
    //   requiring the read bit, and `O_NOFOLLOW` still refuses a symlink
    //   outright (`ELOOP`), so no `fstat` check is needed.
    // - Any other Unix host has no traversal-only open; fall back to `O_RDONLY`
    //   + `O_NOFOLLOW` there (the pre-fix behaviour, which refuses a symlink).
    #[cfg(target_os = "linux")]
    let trav_flags = libc::O_PATH | libc::O_NOFOLLOW | libc::O_CLOEXEC;
    #[cfg(target_os = "macos")]
    let trav_flags = libc::O_SEARCH | libc::O_NOFOLLOW | libc::O_CLOEXEC;
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    let trav_flags = libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC;

    // The components of `path`, so the walk can tell the final component (pin
    // it `O_RDONLY`) apart from the intermediates (traverse-only).
    let components: Vec<Component> = path.components().collect();
    let last_normal = components
        .iter()
        .rposition(|c| matches!(c, Component::Normal(_)));

    let mut cur: Option<OwnedFd> = None;
    for (i, comp) in components.iter().enumerate() {
        // Only a `Normal` component is opened `O_NOFOLLOW` as the pinned leaf;
        // the anchor (`/` / `.`) and `..` are structural and use the anchor
        // flags. `is_leaf_normal` marks the single final `Normal` component.
        let is_leaf_normal = Some(i) == last_normal;
        match comp {
            // `/` and `.` are never symlinks; open the anchor without
            // `O_NOFOLLOW` so a legitimate root/relative base is accepted.
            Component::RootDir => {
                let c = CString::new("/".as_bytes()).unwrap();
                cur = Some(open_dir(&c, base_flags)?);
            }
            Component::CurDir => {
                if cur.is_none() {
                    let c = CString::new(".".as_bytes()).unwrap();
                    cur = Some(open_dir(&c, base_flags)?);
                }
            }
            Component::Normal(name) => {
                // A relative path with no explicit `.` anchors at the cwd.
                let dir = match cur.as_ref() {
                    Some(d) => d,
                    None => {
                        let c = CString::new(".".as_bytes()).unwrap();
                        cur = Some(open_dir(&c, base_flags)?);
                        cur.as_ref().unwrap()
                    }
                };
                let c = CString::new(name.as_bytes())
                    .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "path has NUL"))?;
                // Intermediate components are traversal-only; only the final
                // component is opened `O_RDONLY` as the pinned leaf.
                let flags = if is_leaf_normal {
                    step_flags
                } else {
                    trav_flags
                };
                let next = openat_dir(dir.as_raw_fd(), &c, flags)?;
                // On Linux the traversal-only `O_PATH` open does NOT fail on a
                // symlink — it opens the symlink itself — so detect a symlinked
                // intermediate here and refuse, preserving the no-follow
                // guarantee the chain exists to enforce. (On macOS `O_SEARCH` +
                // `O_NOFOLLOW` already failed the open with `ELOOP`, as did
                // `O_NOFOLLOW` on the `O_RDONLY` fallback, so this check is
                // Linux-only.)
                #[cfg(target_os = "linux")]
                if !is_leaf_normal && fd_is_symlink(&next)? {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        "refusing symlinked path component",
                    ));
                }
                cur = Some(next);
            }
            // `..` is resolved against the pinned parent fd — matching the
            // `openat2` backend, which resolves interior `..` against the real
            // parent directory — so both backends enforce one consistent
            // interior-parent policy. Run paths reaching here are first
            // validated by `normalize_run_path`, which REFUSES an interior
            // `..`, so in practice this only ever sees a `..` a caller
            // constructed by hand; resolving it here (rather than refusing)
            // keeps the two backends from diverging on the same input. Note
            // this is *fd-relative* traversal, not path resolution: the
            // kernel's `..` lookup on the pinned fd follows the directory
            // entry, never a symlink.
            Component::ParentDir => {
                let dir = match cur.as_ref() {
                    Some(d) => d,
                    None => {
                        let c = CString::new(".".as_bytes()).unwrap();
                        cur = Some(open_dir(&c, base_flags)?);
                        cur.as_ref().unwrap()
                    }
                };
                let c = CString::new("..".as_bytes()).unwrap();
                // No O_NOFOLLOW: `..` is never a symlink, and the lookup is
                // anchored on the pinned parent fd.
                let next = openat_dir(dir.as_raw_fd(), &c, base_flags)?;
                cur = Some(next);
            }
            Component::Prefix(_) => {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "unexpected path prefix",
                ));
            }
        }
    }
    cur.ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "empty working directory path"))
}

#[cfg(test)]
mod normalize_tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn normalize_run_path_resolves_leading_parents_only() {
        // A leading `..` on an absolute path clamps at the root like the kernel.
        let got = normalize_run_path(Path::new("/../a")).unwrap();
        assert_eq!(got, PathBuf::from("/a"));
        // A leading `..` run that climbs past the root clamps at `/`.
        let got = normalize_run_path(Path::new("/../../../../../../..")).unwrap();
        assert_eq!(got, PathBuf::from("/"));
        // A relative input is anchored at the current directory...
        let got = normalize_run_path(Path::new("y")).unwrap();
        assert_eq!(got, std::env::current_dir().unwrap().join("y"));
        // ...and a LEADING `..` on a relative input climbs the trusted anchor
        // (operator shorthand like `--runs-dir ../runs`).
        let got = normalize_run_path(Path::new("../runs")).unwrap();
        let expected = std::env::current_dir()
            .unwrap()
            .parent()
            .unwrap()
            .join("runs");
        assert_eq!(got, expected);
    }

    #[test]
    fn normalize_run_path_rejects_interior_parent() {
        // Interior `name/..` is REFUSED (fail closed), never collapsed: a
        // lexical collapse across a symlinked component is unsafe, and run
        // paths we generate never legitimately contain an interior `..`
        // (maintainer decision, #36 — supersedes the earlier lexical collapse).
        for bad in [
            "/a/b/../c/./d",        // interior `..` after a normal component
            "/a/../../b",           // `..` right after a normal component
            "x/../y",               // interior `..` on a relative input
            "/shared/link/../runs", // the symlinked-ancestor bypass case
            "/runs/../../etc",      // interior climb out of the run tree
        ] {
            let err = normalize_run_path(Path::new(bad)).unwrap_err();
            assert_eq!(
                err.kind(),
                io::ErrorKind::InvalidInput,
                "interior `..` must be refused: {bad}"
            );
        }
    }

    #[test]
    fn normalize_run_path_puts_a_relative_anchor_in_the_same_frame_as_the_runs_root() {
        // Regression for the `C8CTL_NANO_HOME=./state-link` configuration: the
        // worker normalizes the runs root AND the state-home anchor with this
        // same function before `strip_prefix(&anchor)`, so both must land in
        // one absolute lexical frame for the prefix strip (and the tail
        // reattachment onto the canonical anchor) to succeed.
        let cwd = std::env::current_dir().unwrap();

        let anchor = normalize_run_path(Path::new("./state-link")).unwrap();
        assert_eq!(anchor, cwd.join("state-link"));
        let runs_root =
            normalize_run_path(&anchor.join("agent-runs").join("rust-worker-1")).unwrap();
        assert_eq!(
            runs_root.strip_prefix(&anchor).unwrap(),
            Path::new("agent-runs").join("rust-worker-1"),
            "a normalized runs root must strip the normalized anchor"
        );

        // A `..`-relative anchor (e.g. `C8CTL_NANO_HOME=../state-link`) climbs
        // the trusted cwd lexically and still prefixes its own runs root.
        let anchor = normalize_run_path(Path::new("../state-link")).unwrap();
        assert_eq!(anchor, cwd.parent().unwrap().join("state-link"));
        let runs_root = normalize_run_path(&anchor.join("agent-runs")).unwrap();
        assert_eq!(
            runs_root.strip_prefix(&anchor).unwrap(),
            Path::new("agent-runs"),
        );

        // An interior `..` in the anchor itself is refused outright, so a
        // symlinked-anchor bypass cannot be smuggled past the prefix strip.
        let err = normalize_run_path(Path::new("state/./x/../runs")).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidInput);
    }
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;

    fn scratch(tag: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "nano-safecwd-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&root).unwrap();
        std::fs::canonicalize(&root).unwrap()
    }

    /// The child's cwd must be the pinned directory (compared by canonical
    /// path, so platform symlinks like macOS `/var` → `/private/var` do not
    /// confuse the assertion).
    fn child_cwd(handle: &CwdHandle) -> PathBuf {
        let mut cmd = Command::new("pwd");
        cmd.arg("-P");
        handle.apply_std(&mut cmd).expect("arm fchdir");
        let out = cmd.output().expect("run pwd");
        assert!(out.status.success(), "pwd failed");
        let s = String::from_utf8(out.stdout).unwrap();
        PathBuf::from(s.trim())
    }

    #[test]
    fn launches_in_the_pinned_directory() {
        let dir = scratch("happy");
        let handle = CwdHandle::open(&dir).expect("open dir");
        assert_eq!(
            std::fs::canonicalize(child_cwd(&handle)).unwrap(),
            std::fs::canonicalize(&dir).unwrap(),
            "child cwd must be the pinned directory"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    /// `try_clone` returns a second handle to the SAME pinned inode (not a
    /// re-resolution of the path), so a caller that can propagate uses it
    /// instead of the panicking `Clone`. Both handles must launch into the same
    /// directory, and the clone must survive an ancestor swap just like the
    /// original.
    #[test]
    fn try_clone_shares_the_pinned_inode() {
        let dir = scratch("try-clone");
        std::fs::write(dir.join("marker"), b"real").unwrap();
        let handle = CwdHandle::open(&dir).expect("open dir");
        let cloned = handle.try_clone().expect("try_clone the pinned fd");
        assert_eq!(
            std::fs::canonicalize(child_cwd(&cloned)).unwrap(),
            std::fs::canonicalize(&dir).unwrap(),
            "the try_cloned handle must launch in the same pinned inode"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    /// `Clone` and `try_clone` must agree: both dup the same pinned fd, so a
    /// `clone()` (used where infallible) lands in the same inode `try_clone`
    /// (used where fallible) does.
    #[test]
    fn clone_and_try_clone_agree() {
        let dir = scratch("clone-agree");
        let handle = CwdHandle::open(&dir).expect("open dir");
        let a = handle.clone();
        let b = handle.try_clone().expect("try_clone");
        assert_eq!(
            std::fs::canonicalize(child_cwd(&a)).unwrap(),
            std::fs::canonicalize(child_cwd(&b)).unwrap(),
            "clone and try_clone must bind the same pinned inode"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    /// `try_clone` must be genuinely fallible: under descriptor exhaustion
    /// (`EMFILE`) it returns `Err` instead of panicking, so a best-effort
    /// caller (the `execute()` HEAD probes, which degrade a failed probe to
    /// `None` = "HEAD unreadable") can propagate/degrade rather than crash the
    /// worker the way `Clone`'s `expect` would. This is the invariant the
    /// `slot.rs` HEAD-probe fix relies on: `try_clone().ok()`-style degradation
    /// only works if `try_clone` actually yields `Err` on `EMFILE`.
    ///
    /// The exhaustion check lowers the process-wide `RLIMIT_NOFILE` to a full
    /// table, so it must NOT run as an ordinary `#[test]` thread: sibling test
    /// threads share the process and would see spurious `EMFILE` on their own
    /// opens (and their descriptor closures could make this probe unexpectedly
    /// succeed). It therefore runs in an isolated child process: the parent
    /// re-executes the test binary with `NANO_SAFECWD_EMFILE_CHILD` set, the
    /// child runs ONLY this body (no sibling threads) and exits 0 on a genuine
    /// `Err`, and the parent asserts on the child's exit status.
    #[cfg(unix)]
    #[test]
    fn try_clone_is_fallible_under_descriptor_exhaustion() {
        const CHILD_ENV: &str = "NANO_SAFECWD_EMFILE_CHILD";

        if std::env::var_os(CHILD_ENV).is_none() {
            // Parent: spawn the isolated child running only this test body.
            // `--exact` needs the FULL module path; a bare name matches 0 tests
            // and the child would exit 0 without testing anything (a false
            // pass).
            let exe = std::env::current_exe().expect("current test binary");
            let out = Command::new(exe)
                .arg("safecwd::tests::try_clone_is_fallible_under_descriptor_exhaustion")
                .arg("--exact")
                .arg("--nocapture")
                .arg("--test-threads=1")
                .env(CHILD_ENV, "1")
                .output()
                .expect("spawn EMFILE child");
            // Guard against a 0-match filter false-pass: the child must have
            // actually RUN the one test (libtest prints "running 1 test").
            let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
            let stderr = String::from_utf8_lossy(&out.stderr).into_owned();
            assert!(
                stdout.contains("running 1 test") || stderr.contains("running 1 test"),
                "EMFILE child must run exactly one test (filter matched 0?)\nstdout:\n{stdout}\nstderr:\n{stderr}"
            );
            assert!(
                out.status.success(),
                "EMFILE child must observe try_clone -> Err; status={:?}\nstdout:\n{}\nstderr:\n{}",
                out.status.code(),
                stdout,
                stderr
            );
            return;
        }

        // Child (own process, no sibling threads): tighten RLIMIT_NOFILE to a
        // full table so the very next `F_DUPFD_CLOEXEC` fails with EMFILE.
        let dir = scratch("try-clone-emfile");
        let handle = CwdHandle::open(&dir).expect("open dir");

        let mut lim = libc::rlimit {
            rlim_cur: 0,
            rlim_max: 0,
        };
        if unsafe { libc::getrlimit(libc::RLIMIT_NOFILE, &mut lim) } != 0 {
            std::fs::remove_dir_all(&dir).ok();
            return; // cannot read the limit; skip rather than fail spuriously
        }
        let saved = lim;
        // Empirically find the highest soft limit at which a fresh open already
        // fails with EMFILE. Start from a high-water count of the open fds and
        // walk DOWN, probing with a real `open`: each success means the cap
        // still leaves a free slot, so close that fd and lower the cap by one;
        // the first EMFILE means the table is exactly full — which is precisely
        // the state in which the very next `try_clone` dup must fail. (A pure
        // `/proc/self/fd` count is unreliable here: the read_dir fd closes
        // before the probe, so the arithmetic is off by one and the dup can
        // still succeed.)
        let mut cap: libc::rlim_t = std::fs::read_dir("/proc/self/fd")
            .map(|d| d.count() as libc::rlim_t)
            .unwrap_or(256)
            + 1;
        let mut armed = false;
        while cap > 0 {
            lim.rlim_cur = cap;
            if unsafe { libc::setrlimit(libc::RLIMIT_NOFILE, &lim) } != 0 {
                break; // cannot tighten further; give up and skip below
            }
            let probe = unsafe { libc::open(c"/".as_ptr(), libc::O_RDONLY) };
            if probe < 0 {
                // EMFILE (or any failure) at this cap: the table is full.
                armed = true;
                break;
            }
            unsafe { libc::close(probe) };
            cap -= 1;
        }

        let result = if armed {
            Some(handle.try_clone())
        } else {
            None
        };

        // Restore the limit before asserting/cleanup so a failure here does not
        // wedge the rest of the test binary.
        unsafe { libc::setrlimit(libc::RLIMIT_NOFILE, &saved) };
        std::fs::remove_dir_all(&dir).ok();

        let Some(result) = result else {
            return; // could not reach a full fd table on this host; skip
        };
        assert!(
            result.is_err(),
            "try_clone must return Err(EMFILE) under descriptor exhaustion, not panic or succeed"
        );
    }

    #[test]
    fn dup_fd_never_occupies_a_standard_descriptor() {
        // The dup moved into a child's `pre_exec` must be allocated at
        // descriptor 3 or above: with a closed stdin/stdout/stderr a minimum
        // of 0 would let the dup occupy a standard descriptor that the child's
        // stdio setup can then replace before `pre_exec` runs, leaving
        // `fchdir` aimed at a pipe or `/dev/null` (ENOTDIR) instead of the
        // pinned directory.
        use std::os::unix::io::AsRawFd;
        let dir = scratch("dup-min-fd");
        let handle = CwdHandle::open(&dir).expect("open dir");
        for _ in 0..8 {
            let dup = handle.dup_fd().expect("dup the pinned fd");
            assert!(
                dup.as_raw_fd() >= 3,
                "the pre_exec dup must never occupy a standard descriptor, got {}",
                dup.as_raw_fd()
            );
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    /// Regression for the portability finding that the no-follow chain opened
    /// EVERY path component `O_RDONLY`: a run directory beneath a search-only
    /// ancestor (mode `0111`, no read bit) must still pin and launch, because
    /// ordinary traversal needs only the ancestor's search permission, not its
    /// read permission. The leaf is still opened `O_RDONLY`; only the
    /// intermediate ancestors use a traversal-only open. Runs unprivileged
    /// (skipped under root, which bypasses the permission check).
    ///
    /// This exercises [`open_nofollow_chain`] DIRECTLY (not `CwdHandle::open`,
    /// which on a modern Linux kernel resolves via `openat2` and never reaches
    /// the chain): the chain is the sole backend on macOS and pre-5.6 Linux,
    /// which is exactly where the finding bites.
    #[test]
    fn pins_a_run_dir_beneath_a_search_only_ancestor() {
        use std::os::unix::fs::PermissionsExt;
        if unsafe { libc::geteuid() } == 0 {
            eprintln!("skipping: root bypasses the ancestor permission check");
            return;
        }

        let base = scratch("search-only-ancestor");
        let ancestor = base.join("locked");
        let run = ancestor.join("run");
        std::fs::create_dir_all(&run).unwrap();
        // Search-only ancestor: traversal (`x`) is allowed, reading (`r`) is
        // not. The pre-fix chain failed this pin with EACCES.
        std::fs::set_permissions(&ancestor, std::fs::Permissions::from_mode(0o111)).unwrap();

        let opened = open_nofollow_chain(&run);
        // Restore writability so cleanup can descend, whatever the outcome.
        std::fs::set_permissions(&ancestor, std::fs::Permissions::from_mode(0o755)).unwrap();

        let fd = opened.expect(
            "the no-follow chain must pin a run dir beneath a search-only (0111) \
             ancestor: traversal needs only the ancestor's search bit, not its \
             read bit",
        );
        // The pinned fd must be a real, readable directory handle (the leaf is
        // opened `O_RDONLY`): a child `fchdir`s into it at launch.
        let handle = CwdHandle { fd };
        assert_eq!(
            std::fs::canonicalize(child_cwd(&handle)).unwrap(),
            std::fs::canonicalize(&run).unwrap(),
            "the child must launch in the pinned dir beneath the search-only ancestor"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    /// The traversal-only intermediate open must NOT weaken the no-follow
    /// guarantee: a symlinked intermediate is still refused. On Linux, an
    /// `O_PATH` + `O_NOFOLLOW` open returns the link itself rather than
    /// failing, so the chain detects it with `fstat`. This exercises the chain
    /// directly so the Linux-specific check is covered even on a kernel where
    /// `CwdHandle::open` would otherwise use `openat2`.
    #[test]
    fn chain_refuses_a_symlinked_intermediate() {
        let base = scratch("chain-symlink");
        let real = base.join("real");
        std::fs::create_dir_all(real.join("child")).unwrap();
        let link = base.join("link");
        std::os::unix::fs::symlink(&real, &link).unwrap();
        // `<base>/link/child` reaches a real dir only *through* the symlink;
        // the chain must refuse it at the intermediate component.
        assert!(
            open_nofollow_chain(&link.join("child")).is_err(),
            "the no-follow chain must refuse a symlinked intermediate"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn refuses_a_symlinked_leaf() {
        let base = scratch("leaf");
        let real = base.join("real");
        std::fs::create_dir_all(&real).unwrap();
        let link = base.join("link");
        std::os::unix::fs::symlink(&real, &link).unwrap();
        assert!(
            CwdHandle::open(&link).is_err(),
            "a symlinked leaf must be refused"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn refuses_a_symlinked_ancestor() {
        let base = scratch("ancestor");
        let real = base.join("real");
        std::fs::create_dir_all(real.join("child")).unwrap();
        let link = base.join("link");
        std::os::unix::fs::symlink(&real, &link).unwrap();
        // `<base>/link/child` reaches a real dir only *through* the symlink.
        assert!(
            CwdHandle::open(&link.join("child")).is_err(),
            "a path through a symlinked ancestor must be refused"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    /// The core #35 guarantee: once the handle is pinned, swapping an ancestor
    /// for a symlink *between provisioning and launch* cannot redirect the
    /// child — it still lands in the original validated inode, never the
    /// attacker's target.
    #[test]
    fn ancestor_swapped_after_open_does_not_redirect_the_launch() {
        let base = scratch("toctou");
        let ancestor = base.join("ancestor");
        let run = ancestor.join("run");
        std::fs::create_dir_all(&run).unwrap();
        // A marker identifying the real pinned inode.
        std::fs::write(run.join("real-marker"), b"real").unwrap();

        // Provision-time: resolve + pin the validated run dir.
        let handle = CwdHandle::open(&run).expect("open run dir");

        // Attacker swaps the ancestor for a symlink to a directory they control,
        // in the window before launch. The real subtree is moved aside (so the
        // pinned inode stays linked and reachable) and `<base>/ancestor` is
        // repointed at an evil tree, so the *path* `<base>/ancestor/run` now
        // resolves to the attacker's directory.
        let moved = base.join("ancestor-moved");
        std::fs::rename(&ancestor, &moved).unwrap();
        let evil = base.join("evil");
        std::fs::create_dir_all(evil.join("run")).unwrap();
        std::fs::write(evil.join("run").join("evil-marker"), b"attacker").unwrap();
        std::os::unix::fs::symlink(&evil, &ancestor).unwrap();

        // Launch still lands in the pinned inode (now at `moved/run`), never the
        // swapped-in attacker target the path would now resolve to.
        let landed = std::fs::canonicalize(child_cwd(&handle)).unwrap();
        assert_eq!(
            landed,
            std::fs::canonicalize(moved.join("run")).unwrap(),
            "pinned launch must stay in the validated inode after an ancestor swap"
        );
        assert!(
            landed.join("real-marker").exists(),
            "launch must land in the real validated inode"
        );
        assert!(
            !landed.join("evil-marker").exists(),
            "launch must not land in the attacker-controlled target"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    /// `open_child` pins the child *relative to the pinned parent fd*, so
    /// swapping an ancestor for a symlink after the parent was opened cannot
    /// redirect the descent — the child handle still names the real inode.
    #[test]
    fn open_child_survives_an_ancestor_swap() {
        let base = scratch("child-swap");
        let ancestor = base.join("ancestor");
        let run = ancestor.join("run");
        std::fs::create_dir_all(run.join("repo")).unwrap();
        std::fs::write(run.join("repo").join("real-marker"), b"real").unwrap();

        let run_handle = CwdHandle::open(&run).expect("open run dir");

        // Swap the ancestor for a symlink to an attacker tree.
        let moved = base.join("ancestor-moved");
        std::fs::rename(&ancestor, &moved).unwrap();
        let evil = base.join("evil");
        std::fs::create_dir_all(evil.join("run").join("repo")).unwrap();
        std::fs::write(
            evil.join("run").join("repo").join("evil-marker"),
            b"attacker",
        )
        .unwrap();
        std::os::unix::fs::symlink(&evil, &ancestor).unwrap();

        // The child open is anchored on the pinned run-dir fd, so it lands in
        // the real inode even though the path now resolves to the attacker.
        let child = run_handle.open_child(std::ffi::OsStr::new("repo")).unwrap();
        let landed = std::fs::canonicalize(child_cwd(&child)).unwrap();
        assert_eq!(
            landed,
            std::fs::canonicalize(moved.join("run").join("repo")).unwrap(),
            "open_child must stay under the pinned parent after an ancestor swap"
        );
        assert!(landed.join("real-marker").exists());
        assert!(!landed.join("evil-marker").exists());

        // And the handle still reports the pinned inode's current path.
        let reported = child.path().expect("path of pinned child");
        assert_eq!(
            std::fs::canonicalize(reported).unwrap(),
            std::fs::canonicalize(moved.join("run").join("repo")).unwrap(),
            "path() must name the pinned inode, not a pre-swap pathname"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn open_child_refuses_a_symlinked_child() {
        let base = scratch("child-link");
        let run = base.join("run");
        std::fs::create_dir_all(&run).unwrap();
        let outside = base.join("outside");
        std::fs::create_dir_all(&outside).unwrap();
        std::os::unix::fs::symlink(&outside, run.join("repo")).unwrap();
        let run_handle = CwdHandle::open(&run).expect("open run dir");
        assert!(
            run_handle.open_child(std::ffi::OsStr::new("repo")).is_err(),
            "a symlinked child must be refused"
        );
        std::fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn interior_parent_resolves_against_the_pinned_parent() {
        // Both backends accept an interior `..` and resolve it identically —
        // against the real parent directory, never through a symlink. The
        // walked-through `x` must EXIST: the chain opens each component to pin
        // it before the `..` climbs back to the real parent.
        let base = scratch("dotdot");
        let run = base.join("a").join("run");
        std::fs::create_dir_all(&run).unwrap();
        std::fs::create_dir_all(base.join("a").join("x")).unwrap();
        std::fs::write(run.join("marker"), b"real").unwrap();
        let via_parent = base.join("a").join("x").join("..").join("run");
        let handle = CwdHandle::open(&via_parent).expect("open via interior ..");
        let landed = std::fs::canonicalize(child_cwd(&handle)).unwrap();
        assert_eq!(landed, std::fs::canonicalize(&run).unwrap());
        std::fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn parent_dir_at_the_root_clamps_like_the_kernel() {
        // `..` at `/` is a no-op for the kernel (`/..` == `/`); the chain must
        // match so a normalized path can never diverge between backends. This
        // is the fd-relative walk resolving `..` against the pinned root fd.
        let handle = CwdHandle::open(Path::new("/..")).expect("/.. must clamp to /");
        let landed = std::fs::canonicalize(child_cwd(&handle)).unwrap();
        assert_eq!(landed, std::fs::canonicalize(Path::new("/")).unwrap());
    }

    /// `path()` must recover the pinned inode's name WITHOUT ever mutating the
    /// process-global cwd: the supervisor runs a multi-threaded runtime, so a
    /// transient `fchdir` into the pinned dir would make a concurrent thread's
    /// relative-path op resolve against the run dir instead of the real cwd.
    /// A watcher thread samples `getcwd` in a tight loop while the main thread
    /// hammers `path()`; the cwd must never move. (Red against the old
    /// `fchdir`-every-call implementation, which transiently changed it.)
    #[test]
    fn path_never_mutates_the_process_cwd() {
        use std::sync::atomic::{AtomicBool, Ordering};
        use std::sync::Arc;

        let base = scratch("path-no-chdir");
        let run = base.join("run");
        std::fs::create_dir_all(&run).unwrap();
        let handle = CwdHandle::open(&run).expect("open run dir");

        let before = std::env::current_dir().expect("cwd");
        let stop = Arc::new(AtomicBool::new(false));
        let moved = {
            let stop = Arc::clone(&stop);
            let expected = before.clone();
            std::thread::spawn(move || {
                let mut seen_change = false;
                while !stop.load(Ordering::Relaxed) {
                    let mut buf = vec![0u8; libc::PATH_MAX as usize];
                    // SAFETY: `buf` is writable for its length; `getcwd`
                    // NUL-terminates it on success.
                    let ok = unsafe { !libc::getcwd(buf.as_mut_ptr().cast(), buf.len()).is_null() };
                    if ok {
                        let len = buf.iter().position(|&b| b == 0).unwrap_or(0);
                        use std::os::unix::ffi::OsStrExt;
                        let now = Path::new(std::ffi::OsStr::from_bytes(&buf[..len]));
                        if now != expected {
                            seen_change = true;
                        }
                    }
                }
                seen_change
            })
        };

        for _ in 0..5000 {
            let p = handle.path().expect("recover pinned path");
            assert_eq!(
                std::fs::canonicalize(&p).unwrap(),
                std::fs::canonicalize(&run).unwrap(),
                "path() must name the pinned inode"
            );
        }

        stop.store(true, Ordering::Relaxed);
        let observed_change = moved.join().expect("watcher");
        assert!(
            !observed_change,
            "path() transiently changed the process-global cwd"
        );
        let after = std::env::current_dir().expect("cwd");
        assert_eq!(before, after, "process cwd must be unchanged after path()");
        std::fs::remove_dir_all(&base).ok();
    }
}
