//! Spike job loop: activate (optionally leased) → keep the activation alive →
//! run the agent over ACP → complete or fail, fenced by the lease token.
//!
//! Keep-alive = extend the activation timeout every third of the recovery
//! window. With a lease, every command carries the token, so a superseded
//! worker gets 409 instead of silently settling someone else's activation.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use camunda_orchestration_sdk::models::ActivatedJobResult;
use serde_json::{json, Value};
use tokio::sync::watch;

use crate::acp::{Agent, Outcome};
use crate::jobs::{Job, Jobs};

#[derive(Debug, Clone)]
pub struct WorkerOptions {
    pub job_type: String,
    pub worker_name: String,
    /// Whether `worker_name` was auto-generated by `default_name()` (i.e. has
    /// the `<host>-spike-<pid>` shape) rather than supplied via `--name`. Only a
    /// generated name has its trailing `-<pid>` stripped for the stable run-root
    /// namespace; an explicit name is used verbatim, so two explicit names that
    /// happen to share the default's shape (`host-spike-1`, `host-spike-2`) keep
    /// distinct namespaces instead of collapsing together.
    pub name_generated: bool,
    pub agent_program: String,
    pub agent_args: Vec<String>,
    pub recovery_window: Duration,
    pub idle_timeout: Duration,
    pub poll_timeout: Duration,
    pub runs_dir: PathBuf,
    pub with_lease: bool,
    pub max_jobs: Option<usize>,
    /// Keep the N most recent run directories when sweeping; reap older ones.
    pub keep_runs: Option<usize>,
    /// Refuse to take work while free disk under `runs_dir` is below this (MiB).
    pub min_free_mb: Option<u64>,
    /// Reap run directories older than this, on startup and on each sweep.
    pub reap_age: Option<Duration>,
    /// Sweep `runs_dir` for stale directories on this cadence.
    pub reap_interval: Option<Duration>,
}

pub async fn run(jobs: Jobs, opts: WorkerOptions) -> Result<()> {
    // Confine this worker's runs (and its sweeper) to a *stable* per-worker
    // subtree of the configured run root. The namespace must NOT change across
    // a restart: `default_name()` embeds the PID, so keying the subtree on the
    // worker name would move every run to a fresh `.../host-spike-<pid>/` on
    // each launch — a reactivated job's prior cwd would become invisible
    // (breaking checkpoint/resume) and the old PID subtree unreachable by the
    // new worker's sweeper. Instead derive the subtree from the host plus the
    // job type — stable for a given worker role across restarts, while still
    // separating workers that run different job types. Cross-process safety
    // (two live workers, or a worker vs. a stale run) is handled by the
    // per-job active markers + the synchronized sweeper below, not by the path.
    let opts = {
        let mut opts = opts;
        // Canonicalize the run root so every derived path (the per-job cwd, the
        // AGENT_RESULT_FILE path handed to the agent, and the path `finalize`
        // reads back) is absolute. A relative `--runs-dir` would otherwise make
        // the agent resolve its result file under `cwd/cwd/...` while the worker
        // reads a different (relative) path.
        // `canonicalize` fails when the run root does not exist yet. Falling
        // back to the raw value would leave a relative `--runs-dir` relative,
        // so the agent (whose cwd is already the per-job dir) would resolve its
        // result file under a duplicated `cwd/cwd/...` path that `finalize`
        // cannot read. Anchor the fallback to an absolute path instead.
        let canonical = std::fs::canonicalize(&opts.runs_dir).unwrap_or_else(|_| {
            if opts.runs_dir.is_absolute() {
                opts.runs_dir.clone()
            } else {
                std::env::current_dir()
                    .map(|cwd| cwd.join(&opts.runs_dir))
                    .unwrap_or_else(|_| opts.runs_dir.clone())
            }
        });
        let ns = stable_namespace(&opts.worker_name, &opts.job_type, opts.name_generated);
        opts.runs_dir = canonical.join(ns);
        opts
    };
    let mut done = 0usize;
    log(&format!(
        "worker {} polling {:?} (recovery window {}s, poll {}s, lease {}, job api {})",
        opts.worker_name,
        opts.job_type,
        opts.recovery_window.as_secs(),
        opts.poll_timeout.as_secs(),
        if opts.with_lease { "on" } else { "off" },
        jobs.backend()
    ));

    // Housekeeping: make sure the run root exists before taking any work — a
    // misconfigured/unwritable run root should fail loudly here, not silently
    // burn a job's retries when its cwd can't be created. Then sweep stale run
    // dirs on startup and keep sweeping on the configured cadence.
    std::fs::create_dir_all(&opts.runs_dir)
        .with_context(|| format!("creating run root {}", opts.runs_dir.display()))?;
    // Paths of runs that are currently executing; the sweeper must never reap a
    // live agent's cwd, even under `--keep-runs 0` or when another worker's runs
    // push it out of the newest set.
    let active: Arc<Mutex<HashSet<PathBuf>>> = Arc::new(Mutex::new(HashSet::new()));
    sweep_runs(&opts, &active);
    if let Some(interval) = opts.reap_interval.filter(|d| !d.is_zero()) {
        let sweep_opts = opts.clone();
        let sweep_active = active.clone();
        tokio::spawn(async move {
            loop {
                tokio::time::sleep(interval).await;
                sweep_runs(&sweep_opts, &sweep_active);
            }
        });
    }

    loop {
        if opts.max_jobs.is_some_and(|m| done >= m) {
            return Ok(());
        }
        // Disk-space floor: refuse to take work when free space under the run
        // directory is below the configured floor, before touching the engine.
        if let Some(floor) = opts.min_free_mb {
            if let Some(free) = free_mb(&opts.runs_dir) {
                if free < floor {
                    log(&format!(
                        "free disk {free}MB under {} is below the floor of {floor}MB; refusing to take work",
                        opts.runs_dir.display()
                    ));
                    return Ok(());
                }
            } else {
                log(&format!(
                    "could not determine free disk under {}; refusing to take work below the {floor}MB floor",
                    opts.runs_dir.display()
                ));
                return Ok(());
            }
        }
        let batch = match jobs
            .activate(
                &opts.job_type,
                &opts.worker_name,
                opts.recovery_window,
                opts.poll_timeout,
                opts.with_lease,
            )
            .await
        {
            Ok(b) => b,
            Err(e) => {
                log(&format!("activation failed: {e:#}; retrying in 5s"));
                tokio::time::sleep(Duration::from_secs(5)).await;
                continue;
            }
        };
        for job in batch {
            if opts.with_lease && job.lease.is_none() {
                // Same fail-loud rule as the SDK: never run a job we can't fence.
                anyhow::bail!(
                    "asked for a lease but job {} came back without a lease token; refusing to run unfenced",
                    job.job.job_key.value()
                );
            }
            handle(&jobs, &opts, &active, job).await;
            done += 1;
        }
    }
}

async fn handle(
    jobs: &Jobs,
    opts: &WorkerOptions,
    active: &Arc<Mutex<HashSet<PathBuf>>>,
    Job { job, lease }: Job,
) {
    let key = job.job_key.value().to_string();
    let cwd = opts.runs_dir.join(&key);
    // Claim this cwd against the background sweeper for the run's whole lifetime.
    // Because the run root is a *stable* namespace shared by every worker of the
    // same host+job type (the PID is stripped from the path), an in-process
    // `HashSet` alone cannot stop *another* worker's sweeper from reaping our
    // live cwd. So we also drop a cross-process liveness marker recording our
    // PID: a foreign sweeper reads it, sees the owner process is alive, and
    // skips the directory.
    //
    // Atomically claim this cwd against foreign sweepers before anything else:
    // (re)create the run dir AND stamp our liveness marker *under the same per-run
    // marker lock the sweeper must hold to delete*, so a foreign sweeper's locked
    // check-then-remove cannot interleave between the directory becoming claimable
    // and the marker appearing. This closes the reactivation race, where the dir
    // already exists with an old mtime and no marker (its previous owner removed
    // it on completion) and would otherwise be immediately eligible for reaping in
    // the window between the create and the marker write. Writing the marker also
    // bumps the dir's mtime, keeping it out of the stale set on every later sweep.
    //
    // The claim is MANDATORY: if it cannot be established the worker must not run
    // the agent, because a foreign sweeper would interpret the missing marker as a
    // dead run and could delete this live cwd. The job is already activated
    // (leased), so a bare `return` would strand it leased until its timeout; route
    // the failure through the same `jobs.fail`/retry path as a `run_agent` error
    // so a transient run-dir failure is retried promptly.
    if let Err(e) = claim_run_dir(&cwd) {
        let msg = format!("cannot claim run dir {}: {e:#}", cwd.display());
        log(&format!("job {key}: {msg}; failing for retry"));
        if let Err(e2) = jobs
            .fail(
                &key,
                (job.retries - 1).max(0),
                &truncate(&msg, 2000),
                &lease,
            )
            .await
        {
            log(&format!(
                "job {key}: fail failed: {e2:#} (original error: {msg})"
            ));
        }
        return;
    }
    active.lock().unwrap().insert(cwd.clone());
    let _guard = ActiveGuard {
        active: active.clone(),
        path: cwd.clone(),
    };
    // Clear any stale result file from a prior activation of this same run dir,
    // so a later attempt that writes no result cannot forward the previous
    // attempt's PR metadata. A removal failure other than "not found" means a
    // nonempty stale file may survive and be mistaken for this attempt's result,
    // so treat it as a failed activation rather than proceeding with an
    // untrusted result file.
    if let Err(e) = std::fs::remove_file(agent_result_file(&cwd)) {
        if e.kind() != std::io::ErrorKind::NotFound {
            let msg = format!(
                "cannot clear stale result file in run dir {}: {e:#}",
                cwd.display()
            );
            log(&format!("job {key}: {msg}; failing for retry"));
            if let Err(e2) = jobs
                .fail(
                    &key,
                    (job.retries - 1).max(0),
                    &truncate(&msg, 2000),
                    &lease,
                )
                .await
            {
                log(&format!(
                    "job {key}: fail failed: {e2:#} (original error: {msg})"
                ));
            }
            return;
        }
    }
    let started = Instant::now();
    log(&format!(
        "job {key} activated (type {}, retries {}, lease {})",
        job.r#type,
        job.retries,
        lease.as_deref().unwrap_or("none")
    ));

    let refreshes = Arc::new(AtomicUsize::new(0));
    let (lost_tx, mut lost_rx) = watch::channel(false);
    let refresher = tokio::spawn(refresh_loop(
        jobs.clone(),
        key.clone(),
        lease.clone(),
        opts.recovery_window,
        refreshes.clone(),
        lost_tx,
    ));

    let result = tokio::select! {
        r = run_agent(opts, &key, &job) => Some(r),
        _ = lost_rx.wait_for(|lost| *lost) => None,
    };
    let elapsed = started.elapsed().as_secs_f32();
    let n = refreshes.load(Ordering::Relaxed);

    match result {
        None => {
            refresher.abort();
            log(&format!(
                "job {key}: activation lost after {elapsed:.1}s; agent stopped, job NOT settled (the engine will hand it out again)"
            ));
        }
        Some(Ok(out)) => {
            // Keep the lease refresh alive through finalization AND completion:
            // a fallback push may block for up to FALLBACK_PUSH_TIMEOUT, and the
            // completion HTTP call has its own timeout and can outlive the
            // remaining activation window (especially with a small
            // `--recovery-window`). If the refresh task were aborted before
            // `jobs.complete` returns, the activation could expire mid-complete,
            // fencing a successful run. Abort it only once the settle command
            // has returned.
            // `finalize` runs blocking git subprocesses and a `sleep`-based
            // timeout loop (a fallback push may take up to
            // FALLBACK_PUSH_TIMEOUT). Running that inline would occupy a Tokio
            // worker thread; with a small runtime the lease `refresher` above
            // could then be starved and the activation expire before
            // `complete`, fencing a successful job. Offload it to a blocking
            // thread so the runtime stays free to refresh the lease.
            let pr = {
                let runs_dir = opts.runs_dir.clone();
                let key_c = key.clone();
                let out = out.clone();
                match tokio::task::spawn_blocking(move || finalize(&runs_dir, &key_c, &out)).await {
                    Ok(pr) => pr,
                    Err(e) => {
                        log(&format!("job {key}: finalize task failed: {e}"));
                        None
                    }
                }
            };
            let mut vars: HashMap<String, Value> = [
                ("agentResult".to_string(), json!(out.text)),
                ("agentStopReason".to_string(), json!(out.stop_reason)),
                ("agentWorker".to_string(), json!(opts.worker_name)),
            ]
            .into_iter()
            .collect();
            if let Some(pr) = &pr {
                vars.insert("agentPr".to_string(), json!(pr));
            }
            match jobs.complete(&key, vars, &lease).await {
                Ok(()) => log(&format!(
                    "job {key} completed in {elapsed:.1}s: stop={} updates={} tool_calls={} permissions={} refreshes={n} result={:?}",
                    out.stop_reason,
                    out.updates,
                    out.tool_calls,
                    out.permissions_granted,
                    truncate(&out.text, 120)
                )),
                Err(e) => log(&format!("job {key}: complete failed: {e:#}")),
            }
            refresher.abort();
        }
        Some(Err(e)) => {
            let msg = format!("{e:#}");
            // Keep the lease refresher alive until `jobs.fail` returns, exactly
            // as the completion path above does. Aborting it first can let the
            // lease expire before the failure is submitted, so a `fail` issued
            // near the end of the activation window gets fenced — leaving the
            // job active until it times out instead of retrying it promptly.
            let fail_result = jobs
                .fail(
                    &key,
                    (job.retries - 1).max(0),
                    &truncate(&msg, 2000),
                    &lease,
                )
                .await;
            refresher.abort();
            match fail_result {
                Ok(()) => log(&format!(
                    "job {key} failed after {elapsed:.1}s (refreshes={n}): {msg}"
                )),
                Err(e2) => log(&format!(
                    "job {key}: fail failed: {e2:#} (original error: {msg})"
                )),
            }
        }
    }
}

async fn run_agent(opts: &WorkerOptions, key: &str, job: &ActivatedJobResult) -> Result<Outcome> {
    let prompt = job
        .variables
        .get("prompt")
        .and_then(Value::as_str)
        .context("job has no string variable `prompt`")?
        .to_string();
    let cwd = opts.runs_dir.join(key);
    std::fs::create_dir_all(&cwd).with_context(|| format!("creating {}", cwd.display()))?;
    let env = vec![
        ("NANO_JOB_KEY".to_string(), key.to_string()),
        ("NANO_AGENT_NAME".to_string(), opts.worker_name.clone()),
        // The worker itself allocates the per-job result file and hands its path
        // to the agent, so an agent that reports its PR only via a result file
        // works in a real invocation — not only when a test harness happens to
        // inject `AGENT_RESULT_FILE`. `finalize` reads back this same path.
        (
            "AGENT_RESULT_FILE".to_string(),
            agent_result_file(&cwd).to_string_lossy().into_owned(),
        ),
    ];
    let mut agent = Agent::spawn(&opts.agent_program, &opts.agent_args, &cwd, &env)?;
    log(&format!(
        "job {key}: agent pid {} in {}",
        agent.pid().unwrap_or(0),
        cwd.display()
    ));
    let out = agent.run(&cwd, &prompt, opts.idle_timeout).await;
    agent.shutdown().await;
    let out = out?;
    if out.text.trim().is_empty() {
        // A file-only result is valid: the agent wrote its structured result to
        // AGENT_RESULT_FILE without emitting chat text. Only accept it when the
        // file actually holds a parseable JSON result *object* — a
        // present-but-malformed file is not usable output (`finalize` cannot
        // extract a PR from it), so it must not bypass the empty-result failure
        // rule. A scalar JSON value (`null`, `true`, `0`, `"x"`) parses fine but
        // is likewise unusable — `finalize` reads `v.get("pr")`, which only ever
        // matches an object — so require an object here and reject scalars.
        // An *empty* object (`{}`) is likewise unusable: it carries no `pr`
        // (nor any other required field), so treat it the same as a scalar and
        // reject it. Require a non-empty object.
        // Fail when there is truly nothing usable — no text AND no valid result
        // object (c8ctl-plugin-nano#275).
        let rf = agent_result_file(&cwd);
        let has_valid_file = std::fs::read_to_string(&rf)
            .ok()
            .filter(|s| !s.trim().is_empty())
            .and_then(|s| serde_json::from_str::<Value>(&s).ok())
            .is_some_and(|v| v.as_object().is_some_and(|o| !o.is_empty()));
        if !has_valid_file {
            anyhow::bail!(
                "agent finished ({}) without any usable output (no chat text and no valid JSON result object)",
                out.stop_reason
            );
        }
    }
    Ok(out)
}

async fn refresh_loop(
    jobs: Jobs,
    key: String,
    lease: Option<String>,
    window: Duration,
    count: Arc<AtomicUsize>,
    lost: watch::Sender<bool>,
) {
    let every = window / 3;
    let mut failures = 0;
    loop {
        tokio::time::sleep(every).await;
        match jobs.extend(&key, window, &lease).await {
            Ok(()) => {
                failures = 0;
                count.fetch_add(1, Ordering::Relaxed);
            }
            Err(e) => {
                let msg = format!("{e:#}");
                failures += 1;
                log(&format!("job {key}: refresh failed ({failures}): {msg}"));
                // 404 = gone, 409 = superseded by a newer (leased) activation: stop
                // now. Otherwise tolerate one transient error before giving up.
                if msg.contains("404") || msg.contains("409") || failures >= 2 {
                    let _ = lost.send(true);
                    return;
                }
            }
        }
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let mut t: String = s.chars().take(max).collect();
    t.push('…');
    t
}

/// Derive the *stable* run-root namespace for a worker. Keyed on the host plus
/// the job type — never the live PID — so a worker that restarts keeps the same
/// run root and can see (and its sweeper can reap) the runs it owned before the
/// restart. `default_name()` is `<host>-spike-<pid>`; when the name was
/// generated (`name_generated`) we strip that trailing `-<pid>` so the path is
/// restart-stable. An explicit `--name` is used verbatim — never shape-sniffed —
/// so two explicit names that happen to look like the default (`host-spike-1`,
/// `host-spike-2`) keep distinct namespaces instead of collapsing to a shared
/// one and reaping each other's runs. A short identity digest is also appended
/// so roles whose readable form sanitizes to the same string still get distinct
/// namespaces (see below).
fn stable_namespace(worker_name: &str, job_type: &str, name_generated: bool) -> String {
    // Only a *generated* name has its `-<pid>` suffix stripped; an explicit name
    // is kept intact so its identity (including any trailing digits) is honoured.
    let base = if name_generated {
        strip_default_pid_suffix(worker_name)
    } else {
        worker_name
    };
    // Sanitizing to a path-safe component is lossy: distinct identities such as
    // the job types `spike:nano-supervisor` and `spike-nano-supervisor` both
    // collapse to `spike-nano-supervisor`, which would let two different worker
    // roles share one run root and reap each other's retained runs. Keep the
    // readable, restart-stable prefix but append a short deterministic digest
    // of the *raw* (base, job_type) identity so distinct roles never collide.
    let readable = sanitize_component(&format!("{base}-{job_type}"));
    format!("{readable}-{}", identity_digest(base, job_type, name_generated))
}

/// A short, deterministic hex digest of a worker's raw `(base, job_type,
/// name_generated)` identity. Used to disambiguate run-root namespaces whose
/// readable form is lossy (see `stable_namespace`). Uses FNV-1a, a simple
/// non-cryptographic hash with a fully specified, stable output across Rust
/// versions and platforms — unlike `DefaultHasher`, whose keys/algorithm may
/// change between releases and would silently move run roots on upgrade. A
/// domain separator between the fields prevents `("a-b", "c")` from colliding
/// with `("a", "b-c")`. `name_generated` is folded in as a trailing
/// domain-separated discriminator so an explicit `--name` equal to the *stripped*
/// default (`host-spike`) does not share a namespace with a generated
/// `host-spike-<pid>` that strips to the same base — both yield `base =
/// "host-spike"`, so only this flag tells them apart.
fn identity_digest(base: &str, job_type: &str, name_generated: bool) -> String {
    // FNV-1a 64-bit: offset basis 14695981039346656037, prime 1099511628211.
    let mut h: u64 = 14695981039346656037;
    for byte in base
        .bytes()
        .chain(std::iter::once(0u8))
        .chain(job_type.bytes())
        .chain(std::iter::once(0u8))
        .chain(std::iter::once(u8::from(name_generated)))
    {
        h ^= byte as u64;
        h = h.wrapping_mul(1099511628211);
    }
    format!("{h:016x}")
}

/// Strip the default `-spike-<pid>` PID suffix from a worker name, reducing
/// `<host>-spike-<pid>` to `<host>-spike`. Any other name (including explicit
/// `--name`s such as `worker-1`) is returned unchanged, so only the known
/// default shape is collapsed — an explicit numeric suffix is preserved.
fn strip_default_pid_suffix(name: &str) -> &str {
    match name.rsplit_once('-') {
        Some((head, tail))
            if !tail.is_empty()
                && tail.chars().all(|c| c.is_ascii_digit())
                && head.ends_with("-spike") =>
        {
            head
        }
        _ => name,
    }
}

/// Make a string safe to use as a single path component: keep alphanumerics,
/// `-`, `_` and `.`, and replace anything else (path separators, spaces, …)
/// with `-`. Never empty.
fn sanitize_component(s: &str) -> String {
    let out: String = s
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.') {
                c
            } else {
                '-'
            }
        })
        .collect();
    let out = out.trim_matches(['-', '.'].as_ref()).to_string();
    if out.is_empty() {
        "worker".to_string()
    } else {
        out
    }
}

/// Free space in MiB available under `path`, via POSIX `df -Pk` (portable across
/// macOS and Linux). `None` if `df` is unavailable or its output can't be parsed.
fn free_mb(path: &Path) -> Option<u64> {
    let out = std::process::Command::new("df")
        .arg("-Pk")
        .arg(path)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&out.stdout);
    // Data line: `Filesystem 1024-blocks Used Available Capacity Mounted-on`.
    let avail_kib: u64 = text
        .lines()
        .nth(1)?
        .split_whitespace()
        .nth(3)?
        .parse()
        .ok()?;
    Some(avail_kib / 1024)
}

/// Removes a run path from the active set when a job finishes (or its future is
/// dropped/cancelled), so the sweeper stops protecting it.
struct ActiveGuard {
    active: Arc<Mutex<HashSet<PathBuf>>>,
    path: PathBuf,
}

impl Drop for ActiveGuard {
    fn drop(&mut self) {
        // Drop the cross-process liveness marker first so a completed run's dir
        // (retained by `--keep-runs`) is immediately reapable by any sweeper,
        // then release the in-process guard. Only remove the marker if it still
        // names *this* process: if we lost our lease and another worker has
        // since reactivated the same run dir and written its own marker, that
        // marker belongs to the new live owner — erasing it would let a foreign
        // sweeper delete an active cwd.
        //
        // The "is this marker mine? then unlink" read-modify-write runs under
        // the per-run marker lock so it is atomic against a reactivating
        // worker's `claim_run_dir`: the two can no longer interleave such
        // that we read our own PID, a new owner overwrites the marker, and we
        // then delete the new owner's marker (the cross-process TOCTOU). If the
        // lock cannot be acquired (`None`), skip the unlink: leaving our marker
        // is fail-safe (the dir stays protected) whereas an unlocked delete
        // could race a reactivating owner.
        let marker = self.path.join(ACTIVE_MARKER);
        let _ = with_marker_lock(&self.path, || {
            if let Ok(contents) = std::fs::read_to_string(&marker) {
                // While *this* process is alive no other process can hold our
                // PID, so the PID recorded in the marker uniquely identifies us
                // — compare only that, ignoring any start-time token suffix.
                if marker_pid(contents.trim()) == Some(std::process::id()) {
                    let _ = std::fs::remove_file(&marker);
                }
            }
        });
        if let Ok(mut set) = self.active.lock() {
            set.remove(&self.path);
        }
    }
}

/// Filename of the cross-process liveness marker written inside each *active*
/// run directory. It records the owning worker's PID together with a
/// PID-reuse-resistant start-time token (`"<pid>:<start>"`; see
/// [`own_marker_token`]) so a sweeper in a different process (sharing the same
/// stable run root) can distinguish a live run from an orphaned one — even after
/// a crashed worker's PID has been recycled by an unrelated process.
const ACTIVE_MARKER: &str = ".nano-active";

/// Filename of the **single, run-root-wide** advisory lock guarding all
/// read/modify/write of any run's active marker and every reap-vs-reactivation.
/// [`lock_path_for`] places exactly *one* such lock in the run root (which the
/// sweeper never removes) and shares it across every run directory under that
/// root — rather than one lock file per run dir. This keeps the lock inode
/// stable forever and **bounds lock files to one per run root**, so distinct
/// job keys can no longer leave a permanent `.<key>.lock` sidecar each and grow
/// the run root without bound (which would undermine `--reap-age`/`--keep-runs`
/// and the disk-space guard). The lock file is **never unlinked** (only its
/// advisory lock is taken and released), so there is no open-vs-unlink inode
/// race on the lock itself. Serializing all run dirs under a root against each
/// other is strictly stronger than per-dir locking and adds no meaningful
/// contention: the sweep already holds the in-process active-set lock for its
/// whole pass, and claims/completions take the lock only briefly. It exists
/// solely to serialize marker access and is not itself a liveness signal.
const RUN_ROOT_LOCK: &str = ".nano-runs.lock";

/// Filename of the per-run *retention* sentinel. `finalize` writes it into a run
/// directory whose committed work was captured on a local fallback branch that
/// could **not** be pushed (offline / no remote). While it exists, [`sweep_runs`]
/// must never reap the directory: it is the only surviving copy of that work
/// until it is durably pushed. Unlike the liveness marker it is not PID-scoped —
/// it is a durable "do not delete, unsaved work here" flag, cleared only when an
/// operator has recovered the branch and removes the directory.
const RETAIN_MARKER: &str = ".nano-retain";

/// Filename of the per-run result file the worker allocates and hands to the
/// agent via `AGENT_RESULT_FILE`; the agent writes its structured result
/// (including any opened `pr`) here and [`finalize`] reads it back. Owning the
/// path in the worker is what makes the result channel work in a real
/// invocation rather than only when a harness injects the variable.
const AGENT_RESULT_FILE: &str = ".nano-agent-result.json";

/// The absolute path of a run directory's [`AGENT_RESULT_FILE`].
fn agent_result_file(cwd: &Path) -> PathBuf {
    cwd.join(AGENT_RESULT_FILE)
}

/// The path of the advisory lock serializing access to run-directory liveness
/// markers. A **single** lock is shared by every run directory under the same
/// run root: it lives in the run root itself — the parent the sweeper never
/// removes — so its inode is stable across any run dir's removal and
/// recreation, and, crucially, there is exactly **one** lock file per run root
/// instead of one accumulating per job key.
///
/// A per-run sidecar lock (one `.<name>.lock` beside each run dir) would also be
/// safe against the inode race, but the sweep only ever removes run
/// *directories*, never these sidecars, so with distinct job keys over time they
/// would pile up one-per-job forever — unbounded metadata/disk growth that
/// defeats `--reap-age`/`--keep-runs` and the disk-space guard. Unlinking them
/// is not an option either: a worker blocked in `flock` on a sidecar the sweeper
/// then unlinks would hold an orphaned inode while a later opener creates a fresh
/// one, splitting the lock and reintroducing the reap-vs-reactivation race. A
/// single, never-unlinked run-root lock sidesteps both problems at once.
///
/// If the lock instead lived *inside* the run dir, a worker blocked in `flock`
/// on the old lock could be holding an inode the sweeper's `remove_dir_all` has
/// already unlinked; on resuming it would recreate the dir and stamp a live
/// marker while still holding that unreachable inode, and a later sweep opening
/// a *fresh* lock inode would reap the now-live cwd.
fn lock_path_for(dir: &Path) -> PathBuf {
    match dir.parent() {
        Some(parent) => parent.join(RUN_ROOT_LOCK),
        // A run dir with no parent (filesystem root) cannot be reaped by the
        // sweeper anyway; fall back to an in-dir lock.
        None => dir.join(RUN_ROOT_LOCK),
    }
}

/// Serialize a marker read/modify/write through an exclusive advisory lock on
/// the stable, run-root-wide [`lock_path_for`] file (in the run root, not inside
/// any reapable run dir), so a completing worker's ownership-check-then-unlink
/// and a reactivating worker's marker write are mutually exclusive (closing the
/// read-then-unlink TOCTOU). Dropping the file closes its fd, releasing the
/// lock.
///
/// Returns `Some(f())` only when the lock was actually held for the whole
/// closure; returns `None` — running the closure NOT at all — when the lock
/// could not be acquired (the lock file can't be opened, or `flock` fails for a
/// reason other than a retryable `EINTR`). Callers must treat `None` as "the
/// operation was not serialized" and act fail-safe: a claim fails the job, a
/// sweep skips the reap. This avoids silently running the closure unlocked,
/// which would let a foreign sweeper delete a live cwd (issue: flock failures
/// were previously ignored). On non-unix there is no portable advisory lock, so
/// the closure runs and `Some` is returned unconditionally (documented
/// platform limitation; run roots are host-local).
#[cfg(unix)]
fn with_marker_lock<T>(dir: &Path, f: impl FnOnce() -> T) -> Option<T> {
    use std::os::unix::io::AsRawFd;
    let file = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(false)
        .open(lock_path_for(dir))
        .ok()?;
    // LOCK_EX blocks until the lock is ours; a crashed holder's lock is
    // auto-released by the kernel, so this cannot wedge on a dead worker. Retry
    // on EINTR (a signal interrupted the blocking wait); any other error means
    // we could not serialize, so report failure (`None`) instead of running the
    // closure unlocked and racing a concurrent sweeper.
    loop {
        if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_EX) } == 0 {
            break;
        }
        if std::io::Error::last_os_error().raw_os_error() != Some(libc::EINTR) {
            return None;
        }
    }
    let result = f();
    drop(file);
    Some(result)
}

#[cfg(not(unix))]
fn with_marker_lock<T>(_dir: &Path, f: impl FnOnce() -> T) -> Option<T> {
    Some(f())
}

/// Record this process as the live owner of `cwd` by writing its PID into the
/// run's liveness marker, under the marker lock. **Test-only**: production
/// reactivation goes through [`claim_run_dir`], which stamps the same marker
/// under the lock *together with* the directory (re)creation. The unit tests
/// use this to simulate a prior/foreign owner having claimed a run dir. Returns
/// an error if the marker cannot be written or the lock cannot be acquired.
#[cfg(test)]
fn write_active_marker(cwd: &Path) -> Result<()> {
    let token = own_marker_token();
    with_marker_lock(cwd, || {
        std::fs::write(cwd.join(ACTIVE_MARKER), &token)
            .with_context(|| format!("writing {}", cwd.join(ACTIVE_MARKER).display()))
    })
    .unwrap_or_else(|| {
        Err(anyhow::anyhow!(
            "could not acquire marker lock for {}",
            cwd.display()
        ))
    })
}

/// Atomically claim `cwd` for this worker against foreign sweepers: (re)create
/// the run directory and stamp our liveness marker *under the per-run marker
/// lock the sweeper must also hold to delete*, so a foreign sweeper's locked
/// check-then-remove cannot interleave between the directory becoming claimable
/// and the marker appearing (the reactivation race — a pre-existing dir with an
/// old mtime and no marker).
///
/// The directory is (re)created a second time *inside* the lock: if a sweeper
/// reaped a stale reactivated dir in the narrow window before we acquired the
/// lock, we re-establish it and stamp a live marker under the same lock, so the
/// claim and any concurrent removal are mutually exclusive. In the residual
/// case where the dir *and* its lock file were both reaped before the lock could
/// even be opened — or `flock` otherwise fails — `with_marker_lock` returns
/// `None` and we fail the claim rather than proceed unlocked.
///
/// Fail-loud: any error (including an unacquirable lock) means the claim did not
/// take, and the caller MUST fail the job for retry rather than run the agent in
/// an unprotected cwd.
fn claim_run_dir(cwd: &Path) -> Result<()> {
    // Ensure the dir (and thus the lock file's parent) exists before locking;
    // on reactivation this is a no-op that leaves the possibly-stale dir in place.
    std::fs::create_dir_all(cwd).with_context(|| format!("creating run dir {}", cwd.display()))?;
    let token = own_marker_token();
    with_marker_lock(cwd, || {
        std::fs::create_dir_all(cwd)
            .with_context(|| format!("creating run dir {}", cwd.display()))?;
        // Refuse to steal a run dir from a *live foreign* owner. A normal
        // reactivation finds no marker — the previous owner removed it on
        // completion (see `ActiveGuard::drop`) — so this never blocks the common
        // path. But if our activation raced a still-running owner (e.g. our lease
        // was reissued for the same job before that owner's refresh loop observed
        // the loss), overwriting its live marker here would let both workers share
        // this cwd — concurrent result/git mutation — and hide the first owner
        // from the sweeper behind our PID. Fail-loud instead: the caller fails the
        // job for retry, by which point the old owner has usually dropped its
        // marker. Under the same lock the sweeper holds, this check-then-stamp is
        // atomic against that owner's `ActiveGuard` unlink.
        if foreign_owner_alive_locked(cwd) {
            return Err(anyhow::anyhow!(
                "run dir {} is already held by a live worker; refusing to overwrite its marker",
                cwd.display()
            ));
        }
        std::fs::write(cwd.join(ACTIVE_MARKER), &token)
            .with_context(|| format!("writing {}", cwd.join(ACTIVE_MARKER).display()))
    })
    .unwrap_or_else(|| {
        Err(anyhow::anyhow!(
            "could not acquire marker lock to claim run dir {}",
            cwd.display()
        ))
    })
}

/// Whether `dir` currently holds a live liveness marker owned by a *different*
/// worker process — the guard [`claim_run_dir`] uses to avoid stealing a run dir
/// from a still-running owner. Must be called while holding the marker lock.
///
/// A marker naming *our own* live PID is a self-claim, not a foreign owner, so it
/// never blocks us (while this process runs, no other process can hold our PID —
/// the same reasoning `ActiveGuard::drop` relies on). A missing marker means the
/// cwd is claimable. Mirrors [`marker_owner_alive_locked`]'s fail-safe: a
/// present-but-unreadable/unparseable marker counts as a live foreign owner, so a
/// cwd whose liveness we cannot determine is never overwritten (the caller fails
/// the job for retry rather than risk a double claim).
fn foreign_owner_alive_locked(dir: &Path) -> bool {
    match std::fs::read_to_string(dir.join(ACTIVE_MARKER)) {
        Ok(contents) => {
            let token = contents.trim();
            if marker_pid(token) == Some(std::process::id()) {
                return false;
            }
            marker_token_is_live(token)
        }
        // Fail-safe: only a definitive `NotFound` proves the cwd is unclaimed. A
        // transient permission/I/O error must NOT be read as "claimable" — that
        // could overwrite a live owner's marker. Treat it as a live foreign owner
        // so the claim fails loudly and the job is retried.
        Err(e) => e.kind() != std::io::ErrorKind::NotFound,
    }
}

/// Whether `dir` is a *live* run owned by some still-running worker — i.e. its
/// liveness marker names a PID that is currently alive. Such a directory must
/// never be reaped, even by a foreign worker whose in-process active set can't
/// see it. Fail-safe: a present-but-unparseable marker is treated as live so a
/// possibly-active cwd is never deleted; a missing marker means "not live".
///
/// This lock-taking wrapper is exercised by the unit tests; production callers
/// that already hold the marker lock use [`marker_owner_alive_locked`] directly
/// so a check and its subsequent removal stay atomic under one lock.
#[cfg(test)]
fn marker_owner_alive(dir: &Path) -> bool {
    // Fail-safe on an unacquirable lock: treat as live so a possibly-active cwd
    // is never reaped.
    with_marker_lock(dir, || marker_owner_alive_locked(dir)).unwrap_or(true)
}

/// The liveness read of [`marker_owner_alive`] **without** taking the marker
/// lock — for callers that already hold it (so the check and a subsequent
/// removal can be made atomic under one lock; see [`sweep_runs`]).
fn marker_owner_alive_locked(dir: &Path) -> bool {
    match std::fs::read_to_string(dir.join(ACTIVE_MARKER)) {
        Ok(contents) => marker_token_is_live(contents.trim()),
        // Fail-safe: only a definitive `NotFound` proves the marker is gone and
        // the run is not live. A transient permission/I/O error must NOT be read
        // as "not live" — doing so would let the sweeper reap a directory whose
        // liveness we could not actually determine, contrary to the fail-safe
        // guarantee. Preserve the directory (treat as live) on any other error.
        Err(e) => e.kind() != std::io::ErrorKind::NotFound,
    }
}

/// The liveness-marker payload for *this* worker: `"<pid>:<start-token>"` when a
/// PID-reuse-resistant start token is available, else the legacy bare `"<pid>"`.
/// Pairing the PID with the process's start time lets a foreign sweeper tell a
/// still-running owner from an unrelated process that merely inherited the
/// recycled PID after this worker crashed (see [`process_start_token`]).
fn own_marker_token() -> String {
    let pid = std::process::id();
    match process_start_token(pid) {
        Some(tok) => format!("{pid}:{tok}"),
        None => pid.to_string(),
    }
}

/// The PID recorded in a marker payload, accepting both the current
/// `"<pid>:<start-token>"` form and the legacy bare `"<pid>"`.
fn marker_pid(token: &str) -> Option<u32> {
    token
        .split_once(':')
        .map_or(token, |(pid, _)| pid)
        .trim()
        .parse()
        .ok()
}

/// Whether a marker payload names a process that is still the *same* live owner
/// that wrote it. A live PID alone is not proof: after a crash left the marker
/// behind, that PID can be recycled by an unrelated process, which — under a
/// bare PID check — would protect the stale dir indefinitely (until the
/// unrelated process exits), defeating `--reap-age`/`--keep-runs`. When the
/// marker carries a start-time token we additionally require the live PID's
/// current start time to match, so a recycled PID no longer masks a stale run.
/// Fail-safe throughout: an unparseable PID, or an inability to read the current
/// start time, is treated as live so a possibly-active cwd is never reaped.
fn marker_token_is_live(token: &str) -> bool {
    // A blank recorded start token (e.g. the partial marker write `"<pid>:"`,
    // where a crash interrupted the worker between emitting the PID and its
    // start token) is NOT a real token: comparing a live PID's true `ps` start
    // time against `""` can never match, which would wrongly report the run as
    // not live and reap a possibly-active cwd. Treat an empty/blank start token
    // as absent so we fall back to the PID-only fail-safe path below.
    let (pid_str, recorded_start) = match token.split_once(':') {
        Some((pid, start)) => {
            let start = start.trim();
            (pid, if start.is_empty() { None } else { Some(start) })
        }
        None => (token, None),
    };
    let Ok(pid) = pid_str.trim().parse::<u32>() else {
        return true;
    };
    if !pid_is_live(pid) {
        return false;
    }
    match recorded_start {
        Some(recorded) => match process_start_token(pid) {
            Some(current) => current == recorded,
            None => true,
        },
        None => true,
    }
}

/// A PID-reuse-resistant identity token for `pid`: its wall-clock start time as
/// reported by `ps -o lstart`. Two processes that reuse the same PID over time
/// necessarily have different start times, so comparing this token distinguishes
/// the original owner from an unrelated process that inherited the recycled PID.
/// Portable across Linux and macOS (both ship a `ps` supporting `lstart`), with
/// no platform-specific `/proc` or `sysctl` code — the platform-appropriate
/// fallback is simply `None`, which returns callers to the fail-safe PID-only
/// behaviour. Returns `None` when the start time cannot be determined (no `ps`,
/// an unknown/dead PID, or unexpected output).
fn process_start_token(pid: u32) -> Option<String> {
    if pid == 0 {
        return None;
    }
    let output = std::process::Command::new("ps")
        .args(["-o", "lstart=", "-p", &pid.to_string()])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let start = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if start.is_empty() {
        None
    } else {
        Some(start)
    }
}

/// Best-effort liveness check for a PID on the local host (run roots are
/// host-local, so any worker sharing this namespace is on this host). Uses
/// `kill(pid, 0)`, which performs the kernel's existence/permission checks
/// without sending a signal, so it works uniformly on Linux and macOS (unlike a
/// Linux-only `/proc` probe, which left macOS unable to ever reap orphaned run
/// dirs). Fail-safe: only a definitive `ESRCH` ("no such process") is treated
/// as dead; `EPERM` (alive but unsignalable) and any other error keep the dir.
#[cfg(unix)]
fn pid_is_live(pid: u32) -> bool {
    // Never probe PID 0: `kill(0, 0)` targets the caller's whole process group
    // and returns success, which would misreport a stale/corrupt `0` marker as
    // live and prevent reaping. Zero is not a valid individual process id.
    if pid == 0 {
        return false;
    }
    let ret = unsafe { libc::kill(pid as libc::pid_t, 0) };
    if ret == 0 {
        return true;
    }
    !matches!(
        std::io::Error::last_os_error().raw_os_error(),
        Some(libc::ESRCH)
    )
}

/// Off unix there is no portable liveness probe, so treat a present marker as
/// live and never risk deleting an active cwd; stale dirs are still reaped once
/// their marker is removed on normal completion.
#[cfg(not(unix))]
fn pid_is_live(_pid: u32) -> bool {
    true
}

/// Reap stale per-job run directories: remove immediate subdirectories of
/// `runs_dir` older than `reap_age`, always keeping the `keep_runs` most recent
/// (default 1). Never touches a directory currently backing a running job. A
/// no-op unless `reap_age` is set.
fn sweep_runs(opts: &WorkerOptions, active: &Arc<Mutex<HashSet<PathBuf>>>) {
    let Some(age) = opts.reap_age else {
        return;
    };
    let keep = opts.keep_runs.unwrap_or(1);
    let now = std::time::SystemTime::now();

    let Ok(entries) = std::fs::read_dir(&opts.runs_dir) else {
        return;
    };
    // (path, modified) for each subdirectory, newest first.
    let mut dirs: Vec<(PathBuf, std::time::SystemTime)> = entries
        .flatten()
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .filter_map(|e| {
            let modified = e.metadata().and_then(|m| m.modified()).ok()?;
            Some((e.path(), modified))
        })
        .collect();
    dirs.sort_by_key(|(_, modified)| std::cmp::Reverse(*modified));

    // Hold the active-set lock for the whole sweep so a job cannot register its
    // cwd in the gap between "snapshot the active set" and "remove_dir_all".
    // Checking membership against a cloned set and *then* deleting is a TOCTOU
    // race: a job could register its cwd after the snapshot but before the
    // delete, and we'd remove a live agent's working directory. Deleting while
    // holding the lock makes the active check and the removal atomic w.r.t.
    // registration (which takes the same lock in `handle`/`ActiveGuard`).
    let mut reaped = 0usize;
    {
        let mut active = match active.lock() {
            Ok(g) => g,
            // A poisoned lock means a job panicked while holding it; fail safe by
            // reaping nothing this pass rather than risk deleting a live cwd.
            Err(_) => return,
        };
        for (path, modified) in dirs.into_iter().skip(keep) {
            if active.contains(&path) {
                continue;
            }
            // Durable retention flag: a run whose committed work is only on an
            // unpushed local fallback branch must never be reaped — it is the
            // sole surviving copy until an operator saves it. This unlocked read
            // is only a cheap fast-path skip; the authoritative, race-free
            // re-check happens UNDER the run-root lock in the reap closure below
            // (paired with `retain_run_dir`'s locked write).
            if path.join(RETAIN_MARKER).exists() {
                continue;
            }
            let stale = now
                .duration_since(modified)
                .map(|d| d >= age)
                .unwrap_or(false);
            if !stale {
                continue;
            }
            // Cross-process guard, made atomic against reactivation: hold the
            // shared run-root marker lock across BOTH the liveness check and the
            // removal. Without the shared lock a foreign worker could reactivate
            // this dir (write a live marker under that same lock) in the window
            // between our check returning "not live" and `remove_dir_all`,
            // leaving us to delete a now-live cwd (TOCTOU). Holding the lock for
            // the whole check-then-delete closes that gap. The lock file lives in
            // the run root (see `lock_path_for`), which the sweeper never
            // removes, so `remove_dir_all` cannot unlink the lock inode out from
            // under a worker blocked on it; flock is released when its fd is
            // dropped. If the lock cannot be acquired (`None`),
            // skip this reap (`removed` stays false) rather than delete unlocked
            // — a fail-safe that keeps a possibly-live cwd.
            let removed = with_marker_lock(&path, || {
                // Authoritative retention re-check UNDER the lock. The cheap
                // pre-check above is only a fast-path skip; `retain_run_dir`
                // writes this marker while holding this same run-root lock, so
                // re-reading it here makes retention-write and
                // check-then-remove mutually exclusive. Without it a foreign
                // worker could pass the unlocked pre-check, take the lock, and
                // reap the dir in the window in which `finalize` is retaining
                // an unpushed fallback branch — losing the only copy.
                if path.join(RETAIN_MARKER).exists() {
                    return false;
                }
                if marker_owner_alive_locked(&path) {
                    return false;
                }
                std::fs::remove_dir_all(&path).is_ok()
            })
            .unwrap_or(false);
            if removed {
                // Keep the set tidy if a path was reaped while (somehow) still
                // present; removal is idempotent.
                active.remove(&path);
                reaped += 1;
            }
        }
    }
    if reaped > 0 {
        log(&format!(
            "sweep: reaped {reaped} stale run dir(s) under {} (keep {keep}, age {}s)",
            opts.runs_dir.display(),
            age.as_secs()
        ));
    }
}

/// After a successful agent run, either forward the PR the agent reported or —
/// when it opened none — fall back to a `nano/agent-work/<key>` branch so any
/// committed work is preserved instead of being stranded in the (reapable) run
/// directory. Returns the reported PR reference, if any. Best-effort: finalize
/// never fails the already-successful job.
fn finalize(runs_dir: &Path, key: &str, out: &Outcome) -> Option<String> {
    let cwd = runs_dir.join(key);
    if let Some(pr) = reported_pr(out, &agent_result_file(&cwd)) {
        log(&format!(
            "job {key}: agent reported PR {pr}; forwarding it (no fallback branch)"
        ));
        return Some(pr);
    }
    let branch = format!("nano/agent-work/{key}");
    match push_fallback_branch(&cwd, &branch) {
        Ok(Fallback::Pushed) => log(&format!(
            "job {key}: agent reported no PR; pushed fallback branch {branch} to preserve committed work"
        )),
        Ok(Fallback::LocalOnly) => {
            // The branch exists locally but the push failed (offline / no
            // remote): the run dir now holds the only copy of this work, so
            // retain it against the reaper until it can be saved durably. The
            // retention sentinel is the *sole* cross-process protection for that
            // work once the in-process active guard drops, so if it cannot be
            // written (e.g. disk full / unwritable dir) do NOT silently claim
            // retention succeeded — report it loudly so an operator can rescue
            // the branch before a sweep can reap the now-unprotected dir.
            match retain_run_dir(&cwd) {
                Ok(()) => log(&format!(
                    "job {key}: agent reported no PR; created local fallback branch {branch} but could not push it — retaining run dir {} so the work is not lost",
                    cwd.display()
                )),
                Err(e) => log(&format!(
                    "job {key}: WARNING agent reported no PR and created local fallback branch {branch} but could not push it, AND could not write the retention marker in {}: {e:#} — the run dir is NOT protected against reaping; rescue branch {branch} before it is swept",
                    cwd.display()
                )),
            }
        }
        Ok(Fallback::Nothing) => log(&format!(
            "job {key}: agent reported no PR and no committed work to save; fallback branch {branch} not created"
        )),
        Err(e) => log(&format!(
            "job {key}: agent reported no PR; fallback branch {branch} could not be created: {e:#}"
        )),
    }
    None
}

/// Flag a run directory as holding unsaved work the reaper must not delete.
/// Returns the write result so the caller can surface a failure rather than
/// silently swallow it: the retention sentinel is the only cross-process
/// protection for a local-only fallback branch, so if it cannot be written the
/// caller must report that the work is at risk instead of claiming retention
/// succeeded.
fn retain_run_dir(cwd: &Path) -> std::io::Result<()> {
    // Write the sentinel while holding the shared run-root lock so it is ordered
    // against the reaper's locked check-then-remove (see the reap loop): either
    // the reaper observes the marker under the lock and skips, or it removes the
    // dir before we acquire the lock and our write fails loudly — never a silent
    // write into a dir a foreign worker is concurrently removing. A `None`
    // (lock unavailable) is surfaced as an error for the same reason: retention
    // is the sole cross-process protection for the unpushed branch, so the
    // caller must know it did not take effect.
    with_marker_lock(cwd, || {
        std::fs::write(
            cwd.join(RETAIN_MARKER),
            b"unpushed agent-work fallback branch; retained until durably saved\n",
        )
    })
    .unwrap_or_else(|| {
        Err(std::io::Error::other(
            "could not acquire run-root lock to write retention marker",
        ))
    })
}

/// Extract a PR reference the agent announced, from its `::nano:result::`
/// output marker (the last one wins) or the `result_file` the worker handed it
/// via `AGENT_RESULT_FILE`.
fn reported_pr(out: &Outcome, result_file: &Path) -> Option<String> {
    const MARKER: &str = "::nano:result::";
    // Only the FINAL marker is authoritative. Iterating last-to-first with
    // `find_map` would skip a trailing marker that is malformed or carries no
    // `pr` and silently accept an *earlier* one — forwarding stale PR metadata
    // from a previous turn. Take the last marker alone; if it yields no `pr`,
    // fall back to the result file rather than to an earlier marker.
    if let Some((i, m)) = out.text.rmatch_indices(MARKER).next() {
        let rest = out.text[i + m.len()..].lines().next().unwrap_or("").trim();
        // Tolerate trailing text after the JSON object on the same line.
        let pr = serde_json::Deserializer::from_str(rest)
            .into_iter::<Value>()
            .next()
            .and_then(Result::ok)
            .and_then(|v| pr_of(&v));
        if pr.is_some() {
            return pr;
        }
    }
    if let Ok(text) = std::fs::read_to_string(result_file) {
        if let Ok(v) = serde_json::from_str::<Value>(&text) {
            return pr_of(&v);
        }
    }
    None
}

/// The `pr` field of a result object, if present, a string, and non-blank.
/// A blank `pr` (`{ "pr": "" }`) is treated as *no* PR so `finalize` still
/// takes the fallback-branch path instead of completing with `agentPr: ""`.
fn pr_of(v: &Value) -> Option<String> {
    v.get("pr")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

/// Outcome of an attempted fallback-branch capture.
enum Fallback {
    /// A branch was created and pushed to `origin`.
    Pushed,
    /// A branch was created locally but could not be pushed (offline / no
    /// remote); the run directory holds the only copy and must be retained.
    LocalOnly,
    /// Nothing to save — `cwd` is not a git repo or has no commit.
    Nothing,
}

/// Point a `nano/agent-work/<key>` branch at whatever the agent committed in
/// `cwd` and push it, so unpushed work survives the run dir being reaped.
/// Best-effort — a missing remote or an offline push is not fatal to the
/// (already successful) job, but it is reported as [`Fallback::LocalOnly`] so
/// the caller can retain the directory.
fn push_fallback_branch(cwd: &Path, branch: &str) -> Result<Fallback> {
    let is_repo = git(cwd, &["rev-parse", "--git-dir"])
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !is_repo {
        return Ok(Fallback::Nothing);
    }
    let has_head = git(cwd, &["rev-parse", "--verify", "--quiet", "HEAD"])
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !has_head {
        return Ok(Fallback::Nothing);
    }
    // Check the exit status, not merely whether git launched: `git(...)` reports
    // only that the process ran, not that branch creation succeeded. If
    // `git branch -f` fails (the branch is checked out, the ref is invalid, or
    // the update is rejected) we must NOT push a stale/wrong ref and misreport it
    // as `Pushed`. Signal LocalOnly so the caller retains the run dir — the work
    // is still only in `cwd`.
    let created = git(cwd, &["branch", "-f", branch, "HEAD"])
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !created {
        return Ok(Fallback::LocalOnly);
    }
    // The push runs with a bounded timeout (and terminal prompts disabled) so a
    // missing remote, credential prompt, or unreachable server cannot block the
    // worker indefinitely before it settles the job.
    let pushed = git_with_timeout(
        cwd,
        &["push", "--force-with-lease", "origin", branch],
        FALLBACK_PUSH_TIMEOUT,
    )
    .map(|o| o.map(|o| o.status.success()).unwrap_or(false))
    .unwrap_or(false);
    if pushed {
        Ok(Fallback::Pushed)
    } else {
        Ok(Fallback::LocalOnly)
    }
}

/// Wall-clock budget for the fallback `git push`. Generous enough for a real
/// push over a slow link, bounded enough that a hung/prompting push cannot wedge
/// the async worker before it settles the job.
const FALLBACK_PUSH_TIMEOUT: Duration = Duration::from_secs(120);

/// Run `git <args>` in `cwd`, capturing its output.
fn git(cwd: &Path, args: &[&str]) -> Result<std::process::Output> {
    std::process::Command::new("git")
        .args(args)
        .current_dir(cwd)
        .output()
        .with_context(|| format!("running git {}", args.join(" ")))
}

/// Run `git <args>` in `cwd` with a wall-clock `timeout`, killing the child (and
/// returning `Ok(None)`) if it overruns. Terminal credential prompts are
/// disabled so an auth challenge fails fast instead of blocking on stdin.
///
/// stdout/stderr are sent to `/dev/null` rather than captured: the sole caller
/// (the fallback push) inspects only `status.success()` and discards the bytes,
/// and this polling loop never drains a pipe while waiting for the child to
/// exit. Piping them would let a push (or a chatty server-side hook) that emits
/// more than the OS pipe buffer holds block on a full pipe until the timeout —
/// misclassifying an otherwise-successful push as `LocalOnly`.
fn git_with_timeout(
    cwd: &Path,
    args: &[&str],
    timeout: Duration,
) -> Result<Option<std::process::Output>> {
    use std::process::{Command, Stdio};
    let mut cmd = Command::new("git");
    cmd.args(args)
        .current_dir(cwd)
        .env("GIT_TERMINAL_PROMPT", "0")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    // Put git in its OWN process group so a timeout can terminate the whole
    // group, not just the direct `git` process. `git push` forks a transport
    // (e.g. ssh) and may run hooks; `Child::kill()` signals only the direct
    // child, so a hung transport/hook is reparented to init and runs past the
    // deadline — breaking the bounded-push guarantee and leaking processes
    // across jobs. As group leader (pgid == child pid) the whole group can be
    // reaped on timeout (see `terminate_process_group`).
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        cmd.process_group(0);
    }
    let mut child = cmd
        .spawn()
        .with_context(|| format!("running git {}", args.join(" ")))?;
    let start = Instant::now();
    loop {
        if child.try_wait()?.is_some() {
            return Ok(Some(child.wait_with_output()?));
        }
        if start.elapsed() >= timeout {
            terminate_process_group(&mut child);
            let _ = child.wait();
            log(&format!(
                "finalize: git {} exceeded {}s; terminated",
                args.join(" "),
                timeout.as_secs()
            ));
            return Ok(None);
        }
        std::thread::sleep(Duration::from_millis(50));
    }
}

/// SIGKILL the child's entire process group so a `git push`'s transport (ssh)
/// and any hooks it spawned are reaped, not just the direct `git` process. git
/// is spawned as its own group leader (pgid == child pid), so the negated pid
/// addresses the whole group. Best-effort: a race where the group already exited
/// (ESRCH) is fine. The direct child is also killed as a portable fallback (and
/// on non-Unix platforms, the only action).
fn terminate_process_group(child: &mut std::process::Child) {
    #[cfg(unix)]
    {
        let pgid = child.id() as libc::pid_t;
        unsafe {
            libc::kill(-pgid, libc::SIGKILL);
        }
    }
    let _ = child.kill();
}

pub fn log(msg: &str) {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs_f64())
        .unwrap_or(0.0);
    eprintln!("[{now:.3}] {msg}");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn namespace_strips_pid_suffix_for_stability() {
        // `default_name()` is `<host>-spike-<pid>`; the namespace must drop the
        // PID so a restarted worker keeps the same run root.
        let a = stable_namespace("host-spike-123", "my-job", true);
        let b = stable_namespace("host-spike-456", "my-job", true);
        assert_eq!(a, b, "namespace must be stable across restarts (no PID)");
        assert!(
            a.starts_with("host-spike-my-job-"),
            "readable prefix preserved: {a}"
        );
    }

    #[test]
    fn namespace_separates_job_types() {
        let a = stable_namespace("host-spike-123", "job-a", true);
        let b = stable_namespace("host-spike-123", "job-b", true);
        assert_ne!(a, b, "different job types get different subtrees");
    }

    #[test]
    fn namespace_disambiguates_lossy_sanitization() {
        // `spike:x` and `spike-x` sanitize to the same readable component; the
        // identity digest must still keep their namespaces distinct so the two
        // roles never share (and reap) each other's run root.
        let a = stable_namespace("host-spike-123", "spike:nano-supervisor", true);
        let b = stable_namespace("host-spike-123", "spike-nano-supervisor", true);
        assert_ne!(a, b, "distinct raw job types must not collide");
    }

    #[test]
    fn namespace_keeps_explicit_name_without_pid() {
        // An explicit `--name` with no trailing -<pid> keeps its readable prefix.
        assert!(stable_namespace("alice", "job", false).starts_with("alice-job-"));
    }

    #[test]
    fn namespace_distinguishes_explicit_names_shaped_like_default() {
        // An explicit `--name` that happens to look like the generated default
        // (`host-spike-<n>`) must NOT be shape-sniffed into a stripped, shared
        // namespace: `host-spike-1` and `host-spike-2` supplied explicitly must
        // stay distinct so they never share/reap each other's runs.
        let a = stable_namespace("host-spike-1", "job", false);
        let b = stable_namespace("host-spike-2", "job", false);
        assert!(
            a.starts_with("host-spike-1-job-"),
            "explicit name kept: {a}"
        );
        assert!(
            b.starts_with("host-spike-2-job-"),
            "explicit name kept: {b}"
        );
        assert_ne!(a, b, "explicit names must not collapse to a shared subtree");
        // Whereas the *generated* default of that same shape IS stripped, so a
        // restart (new PID) maps back to the same stable run root.
        let g1 = stable_namespace("host-spike-1", "job", true);
        let g2 = stable_namespace("host-spike-2", "job", true);
        assert_eq!(
            g1, g2,
            "generated default is PID-stripped for restart-stability"
        );
        assert_ne!(a, g1, "explicit and generated forms are not conflated");
    }

    #[test]
    fn namespace_distinguishes_explicit_name_equal_to_stripped_default() {
        // Regression: an explicit `--name host-spike` (already the *stripped*
        // default form) yields `base = "host-spike"`, exactly like a generated
        // `host-spike-<pid>` after its `-<pid>` suffix is stripped. Both share
        // the same readable prefix AND the same (base, job_type), so only the
        // `name_generated` flag distinguishes them — it must, or the two workers
        // would share one run root and reap each other's runs.
        let explicit = stable_namespace("host-spike", "job", false);
        let generated = stable_namespace("host-spike-123", "job", true);
        assert_ne!(
            explicit, generated,
            "explicit name equal to the stripped default must not collide with the generated default"
        );
    }

    #[test]
    fn namespace_preserves_explicit_numeric_names() {
        // Explicit `--name worker-1`/`worker-2` must NOT be mistaken for the
        // default `-spike-<pid>` shape; they keep distinct namespaces.
        let a = stable_namespace("worker-1", "job", false);
        let b = stable_namespace("worker-2", "job", false);
        assert!(a.starts_with("worker-1-job-"));
        assert!(b.starts_with("worker-2-job-"));
        assert_ne!(a, b, "explicit numeric names must not collide");
    }

    #[test]
    fn strip_only_touches_default_spike_shape() {
        assert_eq!(strip_default_pid_suffix("host-spike-99"), "host-spike");
        assert_eq!(strip_default_pid_suffix("worker-1"), "worker-1");
        assert_eq!(strip_default_pid_suffix("plain"), "plain");
        // A numeric tail not preceded by `-spike` is preserved.
        assert_eq!(strip_default_pid_suffix("a-b-7"), "a-b-7");
    }

    #[test]
    fn sanitize_replaces_unsafe_chars() {
        assert_eq!(sanitize_component("a/b c"), "a-b-c");
        assert_eq!(sanitize_component("ok_name-1.2"), "ok_name-1.2");
        assert_eq!(sanitize_component("///"), "worker");
    }

    #[test]
    fn active_marker_roundtrips_and_reads_live() {
        // A written marker names *this* live process, so it reads back as live;
        // once removed, the directory reads as not-live (reapable).
        let dir = std::env::temp_dir().join(format!("ns-marker-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        write_active_marker(&dir).unwrap();
        assert!(marker_owner_alive(&dir), "own PID must read as live");
        std::fs::remove_file(dir.join(ACTIVE_MARKER)).unwrap();
        assert!(!marker_owner_alive(&dir), "no marker means not live");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(unix)]
    #[test]
    fn marker_with_dead_pid_reads_not_live() {
        // PID 0 is never a valid individual process id, so its marker is
        // orphaned: `pid_is_live` rejects it before any `kill(0, 0)` probe
        // (which would otherwise target the caller's process group).
        let dir = std::env::temp_dir().join(format!("ns-dead-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join(ACTIVE_MARKER), "0").unwrap();
        assert!(
            !marker_owner_alive(&dir),
            "a dead PID must read as not live"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(unix)]
    #[test]
    fn marker_with_blank_start_token_reads_live() {
        // A partial marker write `"<live-pid>:"` (a crash between emitting the
        // PID and its start token) leaves an empty start token. It must NOT be
        // compared against the live PID's real `ps` start time — that can never
        // match `""` and would wrongly reap a still-live run dir. An empty start
        // token falls back to the PID-only fail-safe, so our own live PID reads
        // as live.
        let dir = std::env::temp_dir().join(format!("ns-blank-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join(ACTIVE_MARKER),
            format!("{}:", std::process::id()),
        )
        .unwrap();
        assert!(
            marker_owner_alive(&dir),
            "a live PID with a blank start token must read as live (fail-safe)"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(unix)]
    #[test]
    fn marker_with_reused_pid_reads_not_live() {
        // A marker naming a *live* PID but a start-time token that cannot match
        // reality models PID reuse: the original owner crashed (its marker was
        // never cleaned up) and an unrelated process later inherited the PID.
        // The start-time mismatch must expose the run as not live so the stale
        // dir stays reapable, instead of being protected until that unrelated
        // process happens to exit.
        let dir = std::env::temp_dir().join(format!("ns-reuse-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join(ACTIVE_MARKER),
            format!("{}:Thu Jan  1 00:00:00 1970", std::process::id()),
        )
        .unwrap();
        // Only meaningful where a real start token is obtainable; if `ps` cannot
        // provide one on this host the check fail-safes to "live" by design, so
        // skip the assertion there rather than assert the fallback path.
        if process_start_token(std::process::id()).is_some() {
            assert!(
                !marker_owner_alive(&dir),
                "a live PID with a mismatched start token must read as not live (PID reuse)"
            );
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn active_guard_drop_keeps_a_foreign_owners_marker() {
        // If another worker reactivated the same dir and wrote its own marker,
        // dropping our guard must not erase that live owner's marker.
        let dir = std::env::temp_dir().join(format!("ns-guard-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        // A marker owned by a different PID (not us).
        let foreign_pid = std::process::id() + 1;
        std::fs::write(dir.join(ACTIVE_MARKER), foreign_pid.to_string()).unwrap();
        drop(ActiveGuard {
            active: Arc::new(Mutex::new(HashSet::new())),
            path: dir.clone(),
        });
        assert!(
            dir.join(ACTIVE_MARKER).exists(),
            "a foreign owner's marker must survive our guard drop"
        );
        // Our own marker, by contrast, is cleaned up.
        write_active_marker(&dir).unwrap();
        drop(ActiveGuard {
            active: Arc::new(Mutex::new(HashSet::new())),
            path: dir.clone(),
        });
        assert!(
            !dir.join(ACTIVE_MARKER).exists(),
            "our own marker must be removed on guard drop"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(unix)]
    #[test]
    fn claim_run_dir_refuses_a_live_foreign_owner() {
        // A run dir already carrying a *live foreign* owner's marker must not be
        // claimed out from under it: overwriting the marker would let two workers
        // share this cwd (concurrent result/git mutation) and hide the first
        // owner from the sweeper. PID 1 is always alive and never us, so it
        // models a live foreign owner.
        let root = std::env::temp_dir().join(format!("ns-claim-live-{}", std::process::id()));
        let dir = root.join("job-a");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join(ACTIVE_MARKER), "1").unwrap();
        assert!(
            claim_run_dir(&dir).is_err(),
            "claiming a dir held by a live foreign owner must fail loudly"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join(ACTIVE_MARKER))
                .unwrap()
                .trim(),
            "1",
            "a rejected claim must not overwrite the live owner's marker"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[cfg(unix)]
    #[test]
    fn claim_run_dir_takes_an_unclaimed_or_dead_dir() {
        // Both the common reactivation case (the previous owner removed its
        // marker on completion, so none is present) and a dead-owner marker leave
        // the cwd claimable; the claim stamps *our* live marker either way.
        let root = std::env::temp_dir().join(format!("ns-claim-free-{}", std::process::id()));
        // Unclaimed: the dir does not yet exist.
        let fresh = root.join("job-fresh");
        claim_run_dir(&fresh).expect("an unclaimed run dir must be claimable");
        assert!(
            marker_owner_alive(&fresh),
            "claiming an unclaimed dir stamps our live marker"
        );
        // Dead owner: a PID-0 marker is orphaned and must not block reclaiming.
        let stale = root.join("job-stale");
        std::fs::create_dir_all(&stale).unwrap();
        std::fs::write(stale.join(ACTIVE_MARKER), "0").unwrap();
        claim_run_dir(&stale).expect("a dead owner's dir must be re-claimable");
        assert!(
            marker_owner_alive(&stale),
            "reclaiming a dead owner's dir stamps our live marker"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    fn outcome_with(text: &str) -> Outcome {
        Outcome {
            stop_reason: "end_turn".to_string(),
            text: text.to_string(),
            updates: 0,
            tool_calls: 0,
            permissions_granted: 0,
        }
    }

    #[test]
    fn reported_pr_reads_the_last_result_marker() {
        // The `::nano:result::` marker in the agent's output carries the PR; the
        // last one wins, and trailing text on the marker line is tolerated.
        let out = outcome_with(
            "opened a PR::nano:result::{\"status\":\"opened\",\"pr\":\"nanobpm/x#7\"} done",
        );
        let missing = std::env::temp_dir().join("ns-no-such-result.json");
        assert_eq!(reported_pr(&out, &missing).as_deref(), Some("nanobpm/x#7"));
    }

    #[test]
    fn reported_pr_ignores_an_earlier_marker_when_the_last_has_no_pr() {
        // Only the FINAL marker is authoritative: a later result that carries no
        // `pr` must not fall back to an earlier marker's stale PR metadata from a
        // previous turn. With no usable `pr` in the last marker and no result
        // file, the worker reports no PR (and falls back to a nano/agent-work
        // branch) rather than forwarding a stale PR.
        let missing = std::env::temp_dir().join("ns-no-such-result.json");
        let out = outcome_with(
            "::nano:result::{\"status\":\"opened\",\"pr\":\"nanobpm/x#7\"}\n\
             later turn::nano:result::{\"status\":\"opened\"}",
        );
        assert!(
            reported_pr(&out, &missing).is_none(),
            "a trailing marker without a pr must not resurrect an earlier marker's PR"
        );
        // A malformed trailing marker likewise must not fall back to an earlier
        // well-formed one.
        let out = outcome_with(
            "::nano:result::{\"status\":\"opened\",\"pr\":\"nanobpm/x#7\"}\n\
             later turn::nano:result::{not json",
        );
        assert!(
            reported_pr(&out, &missing).is_none(),
            "a malformed trailing marker must not resurrect an earlier marker's PR"
        );
    }

    #[test]
    fn reported_pr_is_none_without_a_pr() {
        // Plain chatter with no marker and no `pr` field reports no PR, so the
        // worker falls back to a `nano/agent-work/` branch.
        let missing = std::env::temp_dir().join("ns-no-such-result.json");
        assert!(reported_pr(&outcome_with("committed but opened no PR"), &missing).is_none());
        let out = outcome_with("::nano:result::{\"status\":\"opened\"}");
        assert!(reported_pr(&out, &missing).is_none());
        // A blank/whitespace `pr` is NOT a reported PR: it must take the no-PR
        // (fallback-branch) path rather than complete with `agentPr: ""`.
        let out = outcome_with("::nano:result::{\"status\":\"opened\",\"pr\":\"   \"}");
        assert!(
            reported_pr(&out, &missing).is_none(),
            "a blank `pr` must be treated as no PR"
        );
    }

    #[test]
    fn reported_pr_reads_the_worker_allocated_result_file() {
        // With no `::nano:result::` marker, the PR is read from the result file
        // the worker handed the agent via `AGENT_RESULT_FILE` — proving the
        // channel works without any harness-injected environment.
        let dir = std::env::temp_dir().join(format!("ns-rf-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rf = agent_result_file(&dir);
        std::fs::write(&rf, r#"{"status":"opened","pr":"nanobpm/y#9"}"#).unwrap();
        assert_eq!(
            reported_pr(&outcome_with("did some work"), &rf).as_deref(),
            Some("nanobpm/y#9")
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn fallback_branch_skips_a_non_repo() {
        // A run directory that is not a git repo has nothing to preserve, so no
        // fallback branch is created (and finalize never fails the job).
        let dir = std::env::temp_dir().join(format!("ns-nofb-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        assert!(
            matches!(
                push_fallback_branch(&dir, "nano/agent-work/k").unwrap(),
                Fallback::Nothing
            ),
            "a non-repo cwd yields no fallback branch"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn retained_run_dir_is_never_reaped() {
        // A run dir flagged as retaining unsaved work (an unpushed fallback
        // branch) carries the retention sentinel and must survive the sweeper.
        let dir = std::env::temp_dir().join(format!("ns-retain-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        retain_run_dir(&dir).unwrap();
        assert!(
            dir.join(RETAIN_MARKER).exists(),
            "retain sets the do-not-reap sentinel"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn marker_lock_serializes_and_never_unlinks_the_lock_file() {
        // The stable lock file guards marker access and lives in the RUN ROOT
        // (never inside a reapable run dir), so removing a run dir never unlinks
        // the lock inode out from under a blocked worker. A single lock is shared
        // by every run dir under the root, so lock files cannot accumulate one
        // per job key. Use a dedicated run root so the shared lock is isolated
        // from other tests/processes that also live under `temp_dir`.
        let root = std::env::temp_dir().join(format!("ns-lock-root-{}", std::process::id()));
        std::fs::create_dir_all(&root).unwrap();
        let dir = root.join("run-a");
        std::fs::create_dir_all(&dir).unwrap();
        // `write_active_marker` takes the lock internally; the guarded closure
        // returns its value. (These calls are never nested in production — doing
        // so would self-deadlock, since flock treats each open fd independently.)
        write_active_marker(&dir).unwrap();
        let ran = with_marker_lock(&dir, || 42);
        assert_eq!(
            ran,
            Some(42),
            "the guarded closure runs under the lock and returns its value"
        );
        assert!(
            marker_owner_alive(&dir),
            "marker written under the lock reads live"
        );
        #[cfg(unix)]
        {
            let lock = lock_path_for(&dir);
            assert!(
                lock.exists(),
                "the lock file persists (never unlinked) for stable, race-free locking"
            );
            assert!(
                !dir.join(RUN_ROOT_LOCK).exists(),
                "the lock lives in the run root, not inside the reapable run dir"
            );
            // A sibling run dir under the same root shares the SAME lock file —
            // lock files are bounded to one per run root, not one per job key.
            let sibling = root.join("run-b");
            std::fs::create_dir_all(&sibling).unwrap();
            assert_eq!(
                lock_path_for(&sibling),
                lock,
                "sibling run dirs share one run-root lock (no per-job accumulation)"
            );
            // Reaping a run dir must not remove the run-root lock.
            let _ = std::fs::remove_dir_all(&dir);
            assert!(
                lock.exists(),
                "removing a run dir leaves the shared run-root lock in place"
            );
        }
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn identity_digest_is_stable_across_rust_versions() {
        // FNV-1a has a fully specified, version-independent output. These
        // expected values were computed once and must never change — if they do,
        // the digest algorithm changed and run-root namespaces would silently
        // move on upgrade, breaking resume/sweeping.
        assert_eq!(
            identity_digest("host-spike", "my-job", true),
            "4e25bd78637a056f"
        );
        assert_eq!(identity_digest("a-b", "c", true), "654d4d9e0313c6b1");
        assert_eq!(identity_digest("a", "b-c", true), "f28ebd9cd7efb9cd");
        // Domain separator: ("a-b", "c") and ("a", "b-c") must differ.
        assert_ne!(
            identity_digest("a-b", "c", true),
            identity_digest("a", "b-c", true)
        );
        // The `name_generated` flag is part of the identity: the same
        // (base, job_type) with a different flag must yield a different digest.
        assert_ne!(
            identity_digest("host-spike", "my-job", true),
            identity_digest("host-spike", "my-job", false)
        );
    }

    #[test]
    fn stale_result_file_is_cleared_before_activation() {
        // A prior activation's result file must not leak into a later attempt:
        // handle() removes it before running the agent.
        let dir = std::env::temp_dir().join(format!("ns-stale-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rf = agent_result_file(&dir);
        std::fs::write(&rf, r#"{"status":"opened","pr":"nanobpm/z#1"}"#).unwrap();
        assert!(rf.exists(), "stale result file written");
        // Simulate the pre-activation cleanup handle() performs.
        let _ = std::fs::remove_file(agent_result_file(&dir));
        assert!(!rf.exists(), "stale result file cleared before activation");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
